import Foundation
/// App UI language + string table. Every user-visible string should go through `L10n.t`.
enum AppUILanguage: String, CaseIterable, Identifiable {
    case system = "system"
    case en = "en"
    case ru = "ru"
    case es = "es"
    case de = "de"
    case fr = "fr"
    case pt = "pt"
    case zhHans = "zh-Hans"
    case ja = "ja"
    case ko = "ko"
    case it = "it"
    case tr = "tr"
    var id: String { rawValue }
    var displayName: String {
        switch self {
        case .system: return L10n.t("appearance.system")
        case .en: return "English"
        case .ru: return "Русский"
        case .es: return "Español"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .pt: return "Português"
        case .zhHans: return "简体中文"
        case .ja: return "日本語"
        case .ko: return "한국어"
        case .it: return "Italiano"
        case .tr: return "Türkçe"
        }
    }
    var resolvedCode: String {
        if self != .system { return rawValue }
        let preferred = Locale.preferredLanguages.first ?? "en"
        let code = Locale(identifier: preferred).language.languageCode?.identifier ?? "en"
        switch code {
        case "ru": return "ru"
        case "es": return "es"
        case "de": return "de"
        case "fr": return "fr"
        case "pt": return "pt"
        case "zh": return "zh-Hans"
        case "ja": return "ja"
        case "ko": return "ko"
        case "it": return "it"
        case "tr": return "tr"
        default: return "en"
        }
    }
}

enum L10n {
    nonisolated(unsafe) static var code: String = "en"

    static func t(_ key: String) -> String {
        if let row = table[key] {
            return row[code] ?? row["en"] ?? key
        }
        return key
    }

    static func tf(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: Locale(identifier: code), arguments: args)
    }

    private static let table: [String: [String: String]] = [
        "adv.clearKeys": ["en": "Clear all API keys", "ru": "Удалить все API-ключи", "es": "Borrar todas las claves API", "de": "Alle API-Schlüssel löschen", "fr": "Effacer toutes les clés API", "pt": "Limpar todas as chaves API", "zh-Hans": "清除所有 API 密钥", "ja": "すべての API キーを消去", "ko": "모든 API 키 지우기", "it": "Cancella tutte le chiavi API", "tr": "Tüm API anahtarlarını sil"],
        "adv.clearLog": ["en": "Clear diagnostics log", "ru": "Очистить лог диагностики", "es": "Borrar registro de diagnóstico", "de": "Diagnoseprotokoll löschen", "fr": "Effacer le journal de diagnostic", "pt": "Limpar log de diagnóstico", "zh-Hans": "清除诊断日志", "ja": "診断ログを消去", "ko": "진단 로그 지우기", "it": "Cancella log di diagnostica", "tr": "Tanılama günlüğünü temizle"],
        "adv.debug": ["en": "Debug mode (keep audio files after transcription)", "ru": "Режим отладки (хранить аудио после транскрибации)", "es": "Modo depuración (conservar audio tras transcribir)", "de": "Debug-Modus (Audiodateien behalten)", "fr": "Mode debug (garder les fichiers audio)", "pt": "Modo debug (manter áudio após transcrição)", "zh-Hans": "调试模式（转写后保留音频）", "ja": "デバッグ（文字起こし後も音声を保持）", "ko": "디버그(변환 후 오디오 유지)", "it": "Modalità debug (mantieni audio dopo trascrizione)", "tr": "Hata ayıklama (yazıya dökmeden sonra ses dosyalarını tut)"],
        "adv.exportLog": ["en": "Export diagnostics log", "ru": "Экспорт лога диагностики", "es": "Exportar registro de diagnóstico", "de": "Diagnoseprotokoll exportieren", "fr": "Exporter le journal de diagnostic", "pt": "Exportar log de diagnóstico", "zh-Hans": "导出诊断日志", "ja": "診断ログを書き出す", "ko": "진단 로그 내보내기", "it": "Esporta log di diagnostica", "tr": "Tanılama günlüğünü dışa aktar"],
        "adv.lastError": ["en": "Last error", "ru": "Последняя ошибка", "es": "Último error", "de": "Letzter Fehler", "fr": "Dernière erreur", "pt": "Último erro", "zh-Hans": "上次错误", "ja": "最後のエラー", "ko": "마지막 오류", "it": "Ultimo errore", "tr": "Son hata"],
        "adv.none": ["en": "None", "ru": "Нет", "es": "Ninguno", "de": "Keiner", "fr": "Aucun", "pt": "Nenhum", "zh-Hans": "无", "ja": "なし", "ko": "없음", "it": "Nessuno", "tr": "Yok"],
        "adv.privacy": ["en": "Privacy: Audio goes only to the selected provider. Keys live in Keychain. Recordings are deleted unless Debug is on.", "ru": "Конфиденциальность: аудио только выбранному провайдеру. Ключи — в Связке ключей. Записи удаляются, если Debug выкл.", "es": "Privacidad: el audio solo al proveedor elegido. Claves en el Llavero. Las grabaciones se borran si Debug está off.", "de": "Datenschutz: Audio nur an den gewählten Anbieter. Schlüssel im Schlüsselbund. Aufnahmen werden gelöscht, außer Debug ist an.", "fr": "Confidentialité : l'audio va seulement au fournisseur choisi. Clés dans le Trousseau. Enregistrements supprimés sauf en debug.", "pt": "Privacidade: áudio só para o provedor escolhido. Chaves no Porta-chaves. Gravações apagadas se Debug estiver off.", "zh-Hans": "隐私：音频仅发送到所选服务商。密钥保存在钥匙串。未开启调试时录音会被删除。", "ja": "プライバシー: 音声は選択したプロバイダーのみへ。キーはキーチェーン。デバッグオフ時は録音を削除。", "ko": "개인정보: 오디오는 선택한 제공자에게만 전송. 키는 키체인. 디버그 꺼지면 녹음 삭제.", "it": "Privacy: l'audio va solo al provider scelto. Chiavi nel Portachiavi. Le registrazioni si cancellano se Debug è off.", "tr": "Gizlilik: Ses yalnızca seçilen sağlayıcıya gider. Anahtarlar Keychain’de. Hata ayıklama kapalıysa kayıtlar silinir."],
        "adv.reset": ["en": "Reset all settings", "ru": "Сбросить все настройки", "es": "Restablecer todos los ajustes", "de": "Alle Einstellungen zurücksetzen", "fr": "Réinitialiser tous les réglages", "pt": "Redefinir todas as configurações", "zh-Hans": "重置所有设置", "ja": "すべての設定をリセット", "ko": "모든 설정 초기화", "it": "Reimposta tutte le impostazioni", "tr": "Tüm ayarları sıfırla"],
        "adv.resetDone": ["en": "Settings reset. Quit and reopen FlowDictate.", "ru": "Настройки сброшены. Закройте и снова откройте FlowDictate.", "es": "Ajustes restablecidos. Cierra y vuelve a abrir FlowDictate.", "de": "Einstellungen zurückgesetzt. FlowDictate neu starten.", "fr": "Réglages réinitialisés. Quittez et rouvrez FlowDictate.", "pt": "Configurações redefinidas. Feche e reabra o FlowDictate.", "zh-Hans": "设置已重置。请退出并重新打开 FlowDictate。", "ja": "設定をリセットしました。FlowDictate を再起動してください。", "ko": "설정이 초기화되었습니다. FlowDictate를 다시 여세요.", "it": "Impostazioni reimpostate. Chiudi e riapri FlowDictate.", "tr": "Ayarlar sıfırlandı. FlowDictate’i kapatıp yeniden açın."],
        "appearance.dark": ["en": "Dark", "ru": "Тёмная", "es": "Oscura", "de": "Dunkel", "fr": "Sombre", "pt": "Escura", "zh-Hans": "深色", "ja": "ダーク", "ko": "다크", "it": "Scura", "tr": "Koyu"],
        "appearance.light": ["en": "Light", "ru": "Светлая", "es": "Clara", "de": "Hell", "fr": "Claire", "pt": "Clara", "zh-Hans": "浅色", "ja": "ライト", "ko": "라이트", "it": "Chiara", "tr": "Açık"],
        "appearance.system": ["en": "System", "ru": "Системная", "es": "Sistema", "de": "System", "fr": "Système", "pt": "Sistema", "zh-Hans": "系统", "ja": "システム", "ko": "시스템", "it": "Sistema", "tr": "Sistem"],
        "dict.autoInsert": ["en": "Insert into active app automatically", "ru": "Автоматически вставлять в активное приложение", "es": "Insertar automáticamente en la app activa", "de": "Automatisch in die aktive App einfügen", "fr": "Insérer automatiquement dans l'app active", "pt": "Inserir automaticamente no app ativo", "zh-Hans": "自动插入到当前应用", "ja": "アクティブなアプリに自動挿入", "ko": "활성 앱에 자동 삽입", "it": "Inserisci automaticamente nell'app attiva", "tr": "Etkin uygulamaya otomatik ekle"],
        "dict.autoInsertOff": ["en": "Auto-insert is off: transcript is only copied to the clipboard.", "ru": "Авто-вставка выкл.: текст только копируется в буфер.", "es": "Inserción auto desactivada: solo se copia al portapapeles.", "de": "Auto-Einfügen aus: nur Zwischenablage.", "fr": "Insertion auto désactivée : copie uniquement.", "pt": "Inserção auto desligada: só copia.", "zh-Hans": "自动插入已关：仅复制到剪贴板。", "ja": "自動挿入オフ：クリップボードのみ。", "ko": "자동 삽입 꺼짐: 클립보드에만 복사.", "it": "Inserimento auto disattivo: solo appunti.", "tr": "Otomatik ekleme kapalı: metin yalnızca panoya kopyalanır."],
        "dict.cancelWhile": ["en": "Cancel while active", "ru": "Отмена во время работы", "es": "Cancelar mientras está activo", "de": "Abbrechen während aktiv", "fr": "Annuler pendant l'activité", "pt": "Cancelar enquanto ativo", "zh-Hans": "活动时取消", "ja": "動作中にキャンセル", "ko": "활성 중 취소", "it": "Annulla mentre attivo", "tr": "Etkin iken iptal"],
        "dict.clipboardRestore": ["en": "Restore previous clipboard after paste", "ru": "Восстановить прежний буфер после вставки", "es": "Restaurar portapapeles anterior tras pegar", "de": "Vorherige Zwischenablage nach Einfügen wiederherstellen", "fr": "Restaurer l'ancien presse-papiers après collage", "pt": "Restaurar área de transferência anterior após colar", "zh-Hans": "粘贴后恢复原先的剪贴板", "ja": "ペースト後に以前のクリップボードを復元", "ko": "붙여넣기 후 이전 클립보드 복원", "it": "Ripristina appunti precedenti dopo l'incolla", "tr": "Yapıştırdıktan sonra önceki panoyu geri yükle"],
        "dict.clipboardRestoreHintOff": ["en": "The transcript stays on the clipboard after paste.", "ru": "После вставки транскрипт остаётся в буфере обмена.", "es": "La transcripción permanece en el portapapeles.", "de": "Das Transkript bleibt in der Zwischenablage.", "fr": "La transcription reste dans le presse-papiers.", "pt": "A transcrição permanece na área de transferência.", "zh-Hans": "粘贴后转写内容仍留在剪贴板。", "ja": "貼り付け後も文字起こしがクリップボードに残ります。", "ko": "붙여넣기 후에도 받아쓴 내용이 클립보드에 남습니다.", "it": "La trascrizione resta negli appunti dopo l'incolla.", "tr": "Yapıştırmadan sonra yazıya dökülen metin panoda kalır."],
        "dict.clipboardRestoreHintOn": ["en": "The transcript is pasted into the app, then removed from the clipboard and replaced with what was there before.", "ru": "Текст вставляется в приложение, затем удаляется из буфера и возвращается то, что было раньше.", "es": "Se pega la transcripción y luego se elimina del portapapeles, restaurando el contenido anterior.", "de": "Transkript wird eingefügt, dann aus der Zwischenablage entfernt und der alte Inhalt wiederhergestellt.", "fr": "Le texte est collé, puis retiré du presse-papiers ; l'ancien contenu est restauré.", "pt": "A transcrição é colada e depois removida da área de transferência; o conteúdo anterior volta.", "zh-Hans": "转写内容粘贴到应用后，会从剪贴板删除并恢复之前的内容。", "ja": "文字起こしを貼り付けた後、クリップボードから削除し以前の内容に戻します。", "ko": "받아쓴 내용을 붙여넣은 뒤 클립보드에서 제거하고 이전 내용을 복원합니다.", "it": "La trascrizione viene incollata, poi rimossa dagli appunti e sostituita con il contenuto precedente.", "tr": "Metin uygulamaya yapıştırılır, ardından panodan silinir ve önceki pano içeriği geri gelir."],
        "dict.copyOnFail": ["en": "Copy to clipboard if insertion fails", "ru": "Копировать в буфер, если вставка не удалась", "es": "Copiar al portapapeles si falla la inserción", "de": "In Zwischenablage kopieren bei Fehler", "fr": "Copier dans le presse-papiers en cas d'échec", "pt": "Copiar se a inserção falhar", "zh-Hans": "插入失败时复制到剪贴板", "ja": "挿入失敗時はクリップボードへ", "ko": "삽입 실패 시 클립보드에 복사", "it": "Copia negli appunti se l'inserimento fallisce", "tr": "Ekleme başarısız olursa panoya kopyala"],
        "dict.customShortcut": ["en": "Custom shortcut", "ru": "Свой шорткат", "es": "Atajo personalizado", "de": "Benutzerdefiniert", "fr": "Raccourci personnalisé", "pt": "Atalho personalizado", "zh-Hans": "自定义快捷键", "ja": "カスタムショートカット", "ko": "사용자 지정 단축키", "it": "Scorciatoia personalizzata", "tr": "Özel kısayol"],
        "dict.defaultMic": ["en": "System default input", "ru": "Системный микрофон по умолчанию", "es": "Entrada predeterminada del sistema", "de": "Systemstandard-Eingabe", "fr": "Entrée par défaut du système", "pt": "Entrada padrão do sistema", "zh-Hans": "系统默认输入", "ja": "システムのデフォルト入力", "ko": "시스템 기본 입력", "it": "Ingresso predefinito di sistema", "tr": "Sistem varsayılan girişi"],
        "dict.input": ["en": "Input", "ru": "Вход", "es": "Entrada", "de": "Eingabe", "fr": "Entrée", "pt": "Entrada", "zh-Hans": "输入", "ja": "入力", "ko": "입력", "it": "Ingresso", "tr": "Giriş"],
        "dict.insertMethod": ["en": "Insertion method", "ru": "Способ вставки", "es": "Método de inserción", "de": "Einfügemethode", "fr": "Méthode d'insertion", "pt": "Método de inserção", "zh-Hans": "插入方式", "ja": "挿入方法", "ko": "삽입 방법", "it": "Metodo di inserimento", "tr": "Ekleme yöntemi"],
        "dict.insertion": ["en": "Text insertion", "ru": "Вставка текста", "es": "Inserción de texto", "de": "Texteinfügung", "fr": "Insertion de texte", "pt": "Inserção de texto", "zh-Hans": "文本插入", "ja": "テキスト挿入", "ko": "텍스트 삽입", "it": "Inserimento testo", "tr": "Metin ekleme"],
        "dict.maxDuration": ["en": "Maximum recording duration", "ru": "Максимальная длительность записи", "es": "Duración máxima de grabación", "de": "Maximale Aufnahmedauer", "fr": "Durée maximale d'enregistrement", "pt": "Duração máxima de gravação", "zh-Hans": "最长录音时长", "ja": "最長録音時間", "ko": "최대 녹음 시간", "it": "Durata massima registrazione", "tr": "Maksimum kayıt süresi"],
        "dict.maxSec": ["en": "Maximum: %d sec", "ru": "Максимум: %d с", "es": "Máximo: %d s", "de": "Maximum: %d s", "fr": "Maximum : %d s", "pt": "Máximo: %d s", "zh-Hans": "最长：%d 秒", "ja": "最長: %d 秒", "ko": "최대: %d초", "it": "Massimo: %d s", "tr": "Maksimum: %d sn"],
        "dict.mic": ["en": "Microphone", "ru": "Микрофон", "es": "Micrófono", "de": "Mikrofon", "fr": "Microphone", "pt": "Microfone", "zh-Hans": "麦克风", "ja": "マイク", "ko": "마이크", "it": "Microfono", "tr": "Mikrofon"],
        "dict.minDuration": ["en": "Minimum recording duration", "ru": "Минимальная длительность записи", "es": "Duración mínima de grabación", "de": "Minimale Aufnahmedauer", "fr": "Durée minimale d'enregistrement", "pt": "Duração mínima de gravação", "zh-Hans": "最短录音时长", "ja": "最短録音時間", "ko": "최소 녹음 시간", "it": "Durata minima registrazione", "tr": "Minimum kayıt süresi"],
        "dict.minSec": ["en": "Minimum: %.1f sec", "ru": "Минимум: %.1f с", "es": "Mínimo: %.1f s", "de": "Minimum: %.1f s", "fr": "Minimum : %.1f s", "pt": "Mínimo: %.1f s", "zh-Hans": "最短：%.1f 秒", "ja": "最短: %.1f 秒", "ko": "최소: %.1f초", "it": "Minimo: %.1f s", "tr": "Minimum: %.1f sn"],
        "dict.modeHold": ["en": "Hold to record; release to transcribe.", "ru": "Удерживайте для записи; отпустите для транскрибации.", "es": "Mantén pulsado para grabar; suelta para transcribir.", "de": "Halten zum Aufnehmen; loslassen zum Transkribieren.", "fr": "Maintenez pour enregistrer ; relâchez pour transcrire.", "pt": "Segure para gravar; solte para transcrever.", "zh-Hans": "按住录音；松开转写。", "ja": "長押しで録音、離すと文字起こし。", "ko": "누르고 있으면 녹음, 놓으면 변환.", "it": "Tieni premuto per registrare; rilascia per trascrivere.", "tr": "Kayıt için basılı tut; bırakınca yazıya dök."],
        "dict.modeToggle": ["en": "Press once to start; press again to stop and transcribe.", "ru": "Одно нажатие — старт; повторное — стоп и транскрибация.", "es": "Pulsa una vez para iniciar; otra para detener y transcribir.", "de": "Einmal drücken zum Starten; erneut zum Stoppen und Transkribieren.", "fr": "Appuyez une fois pour démarrer ; encore pour arrêter et transcrire.", "pt": "Pressione uma vez para iniciar; de novo para parar e transcrever.", "zh-Hans": "按一次开始；再按停止并转写。", "ja": "一度押して開始、もう一度で停止して文字起こし。", "ko": "한 번 눌러 시작, 다시 눌러 중지 후 변환.", "it": "Premi una volta per avviare; di nuovo per fermare e trascrivere.", "tr": "Başlatmak için bir kez bas; durdurmak ve yazıya dökmek için tekrar bas."],
        "dict.mute": ["en": "Mute system audio while recording", "ru": "Отключать звук системы во время записи", "es": "Silenciar audio del sistema al grabar", "de": "Systemton während Aufnahme stummschalten", "fr": "Couper le son système pendant l'enregistrement", "pt": "Silenciar áudio do sistema ao gravar", "zh-Hans": "录音时静音系统音频", "ja": "録音中はシステム音声をミュート", "ko": "녹음 중 시스템 오디오 음소거", "it": "Silenzia audio di sistema durante la registrazione", "tr": "Kayıt sırasında sistem sesini kapat"],
        "dict.needsIM": ["en": "Requires Input Monitoring in Privacy settings.", "ru": "Нужен доступ «Мониторинг ввода» в настройках конфиденциальности.", "es": "Requiere Monitorización de entrada en Privacidad.", "de": "Erfordert Eingabeüberwachung in den Datenschutzeinstellungen.", "fr": "Nécessite Surveillance des entrées dans Confidentialité.", "pt": "Requer Monitoramento de entrada em Privacidade.", "zh-Hans": "需要在隐私设置中开启“输入监控”。", "ja": "プライバシー設定で入力モニタリングが必要です。", "ko": "개인 정보 보호 설정에서 입력 모니터링이 필요합니다.", "it": "Richiede Monitoraggio input nelle impostazioni Privacy.", "tr": "Gizlilik ayarlarında Giriş İzleme gerekir."],
        "dict.outputLang": ["en": "Output language", "ru": "Язык распознавания", "es": "Idioma de salida", "de": "Ausgabesprache", "fr": "Langue de sortie", "pt": "Idioma de saída", "zh-Hans": "识别语言", "ja": "出力言語", "ko": "출력 언어", "it": "Lingua di output", "tr": "Çıktı dili"],
        "dict.pressShortcut": ["en": "Press shortcut… (Esc to cancel)", "ru": "Нажмите сочетание… (Esc — отмена)", "es": "Pulsa el atajo… (Esc para cancelar)", "de": "Kürzel drücken… (Esc zum Abbrechen)", "fr": "Appuyez sur le raccourci… (Esc pour annuler)", "pt": "Pressione o atalho… (Esc para cancelar)", "zh-Hans": "按下快捷键…（Esc 取消）", "ja": "ショートカットを押す…（Escでキャンセル）", "ko": "단축키를 누르세요… (Esc로 취소)", "it": "Premi scorciatoia… (Esc per annullare)", "tr": "Kısayola bas… (Esc iptal)"],
        "dict.refreshMics": ["en": "Refresh microphones", "ru": "Обновить список микрофонов", "es": "Actualizar micrófonos", "de": "Mikrofone aktualisieren", "fr": "Actualiser les microphones", "pt": "Atualizar microfones", "zh-Hans": "刷新麦克风", "ja": "マイクを更新", "ko": "마이크 새로고침", "it": "Aggiorna microfoni", "tr": "Mikrofonları yenile"],
        "dict.shortcut": ["en": "Shortcut", "ru": "Шорткат", "es": "Atajo", "de": "Tastenkürzel", "fr": "Raccourci", "pt": "Atalho", "zh-Hans": "快捷键", "ja": "ショートカット", "ko": "단축키", "it": "Scorciatoia", "tr": "Kısayol"],
        "dict.shortcutMode": ["en": "Shortcut mode", "ru": "Режим шортката", "es": "Modo del atajo", "de": "Kürzelmodus", "fr": "Mode du raccourci", "pt": "Modo do atalho", "zh-Hans": "快捷键模式", "ja": "ショートカットモード", "ko": "단축키 모드", "it": "Modalità scorciatoia", "tr": "Kısayol modu"],
        "dict.shortcutTrigger": ["en": "Shortcut trigger", "ru": "Триггер шортката", "es": "Activador del atajo", "de": "Auslöser", "fr": "Déclencheur", "pt": "Acionador", "zh-Hans": "触发方式", "ja": "トリガー", "ko": "트리거", "it": "Attivazione", "tr": "Kısayol tetikleyici"],
        "dict.trailingNewline": ["en": "Add trailing newline", "ru": "Добавлять перенос строки в конце", "es": "Añadir salto de línea final", "de": "Zeilenumbruch am Ende", "fr": "Ajouter un saut de ligne final", "pt": "Adicionar nova linha no final", "zh-Hans": "末尾添加换行", "ja": "末尾に改行を追加", "ko": "끝에 줄바꿈 추가", "it": "Aggiungi nuova riga finale", "tr": "Sona satır sonu ekle"],
        "dict.trailingSpace": ["en": "Add trailing space", "ru": "Добавлять пробел в конце", "es": "Añadir espacio final", "de": "Leerzeichen am Ende", "fr": "Ajouter un espace final", "pt": "Adicionar espaço no final", "zh-Hans": "末尾添加空格", "ja": "末尾にスペースを追加", "ko": "끝에 공백 추가", "it": "Aggiungi spazio finale", "tr": "Sona boşluk ekle"],
        "error.accessibility": ["en": "Accessibility permission is required to insert text.", "ru": "Для вставки текста нужен Универсальный доступ.", "es": "Se requiere Accesibilidad para insertar texto.", "de": "Bedienungshilfen sind zum Einfügen erforderlich.", "fr": "L'accessibilité est requise pour insérer du texte.", "pt": "É necessária Acessibilidade para inserir texto.", "zh-Hans": "插入文字需要辅助功能权限。", "ja": "テキスト挿入にはアクセシビリティが必要です。", "ko": "텍스트 삽입에는 손쉬운 사용 권한이 필요합니다.", "it": "Serve Accessibilità per inserire testo.", "tr": "Metin eklemek için Erişilebilirlik izni gerekir."],
        "error.eventSource": ["en": "Could not create a keyboard event source for typing.", "ru": "Не удалось создать источник клавиатурных событий.", "es": "No se pudo crear el origen de eventos de teclado.", "de": "Tastatur-Ereignisquelle konnte nicht erstellt werden.", "fr": "Impossible de créer la source d'événements clavier.", "pt": "Não foi possível criar a fonte de eventos do teclado.", "zh-Hans": "无法创建键盘事件源。", "ja": "キーボードイベントソースを作成できません。", "ko": "키보드 이벤트 소스를 만들 수 없습니다.", "it": "Impossibile creare la sorgente eventi tastiera.", "tr": "Yazma için klavye olay kaynağı oluşturulamadı."],
        "general.app": ["en": "App", "ru": "Приложение", "es": "App", "de": "App", "fr": "App", "pt": "App", "zh-Hans": "应用", "ja": "アプリ", "ko": "앱", "it": "App", "tr": "Uygulama"],
        "general.appearance": ["en": "Appearance", "ru": "Оформление", "es": "Apariencia", "de": "Erscheinungsbild", "fr": "Apparence", "pt": "Aparência", "zh-Hans": "外观", "ja": "外観", "ko": "모양", "it": "Aspetto", "tr": "Görünüm"],
        "general.launchAtLogin": ["en": "Launch at login", "ru": "Запускать при входе в систему", "es": "Abrir al iniciar sesión", "de": "Bei Anmeldung starten", "fr": "Lancer à la connexion", "pt": "Abrir ao iniciar sessão", "zh-Hans": "登录时启动", "ja": "ログイン時に起動", "ko": "로그인 시 실행", "it": "Avvia all'accesso", "tr": "Girişte başlat"],
        "general.menuBar": ["en": "Show menu bar icon", "ru": "Показывать иконку в строке меню", "es": "Mostrar icono en la barra de menús", "de": "Menüleistensymbol anzeigen", "fr": "Afficher l'icône dans la barre de menus", "pt": "Mostrar ícone na barra de menus", "zh-Hans": "显示菜单栏图标", "ja": "メニューバーにアイコンを表示", "ko": "메뉴 막대 아이콘 표시", "it": "Mostra icona nella barra dei menu", "tr": "Menü çubuğu simgesini göster"],
        "general.overlay": ["en": "Recording overlay", "ru": "Оверлей записи", "es": "Superposición de grabación", "de": "Aufnahme-Overlay", "fr": "Superposition d'enregistrement", "pt": "Overlay de gravação", "zh-Hans": "录音浮层", "ja": "録音オーバーレイ", "ko": "녹음 오버레이", "it": "Overlay di registrazione", "tr": "Kayıt katmanı"],
        "general.overlayPosition": ["en": "Overlay position", "ru": "Позиция оверлея", "es": "Posición de la superposición", "de": "Overlay-Position", "fr": "Position de la superposition", "pt": "Posição do overlay", "zh-Hans": "浮层位置", "ja": "オーバーレイの位置", "ko": "오버레이 위치", "it": "Posizione overlay", "tr": "Katman konumu"],
        "general.privatePreview": ["en": "Keep preview private (no text on overlay)", "ru": "Скрывать текст в превью оверлея", "es": "Mantener vista previa privada", "de": "Vorschau privat halten", "fr": "Garder l'aperçu privé", "pt": "Manter prévia privada", "zh-Hans": "预览保密（浮层不显示文字）", "ja": "プレビューを非表示", "ko": "미리보기 비공개", "it": "Mantieni anteprima privata", "tr": "Önizlemeyi gizli tut (katmanda metin yok)"],
        "general.showMic": ["en": "Show microphone label", "ru": "Показывать микрофон", "es": "Mostrar micrófono", "de": "Mikrofon anzeigen", "fr": "Afficher le microphone", "pt": "Mostrar microfone", "zh-Hans": "显示麦克风", "ja": "マイクを表示", "ko": "마이크 표시", "it": "Mostra microfono", "tr": "Mikrofon etiketini göster"],
        "general.showOverlay": ["en": "Show recording overlay", "ru": "Показывать оверлей записи", "es": "Mostrar superposición de grabación", "de": "Aufnahme-Overlay anzeigen", "fr": "Afficher la superposition d'enregistrement", "pt": "Mostrar overlay de gravação", "zh-Hans": "显示录音浮层", "ja": "録音オーバーレイを表示", "ko": "녹음 오버레이 표시", "it": "Mostra overlay di registrazione", "tr": "Kayıt katmanını göster"],
        "general.showPreview": ["en": "Show transcript preview after success", "ru": "Превью текста после успеха", "es": "Vista previa del texto tras el éxito", "de": "Transkriptvorschau nach Erfolg", "fr": "Aperçu du texte après succès", "pt": "Prévia do texto após sucesso", "zh-Hans": "成功后显示转写预览", "ja": "成功後に文字起こしプレビュー", "ko": "성공 후 받아쓰기 미리보기", "it": "Anteprima trascrizione dopo il successo", "tr": "Başarıdan sonra metin önizlemesi"],
        "general.showProvider": ["en": "Show provider name", "ru": "Показывать имя провайдера", "es": "Mostrar nombre del proveedor", "de": "Anbietername anzeigen", "fr": "Afficher le nom du fournisseur", "pt": "Mostrar nome do provedor", "zh-Hans": "显示服务商名称", "ja": "プロバイダー名を表示", "ko": "제공자 이름 표시", "it": "Mostra nome provider", "tr": "Sağlayıcı adını göster"],
        "general.showTimer": ["en": "Show timer while recording", "ru": "Показывать таймер во время записи", "es": "Mostrar temporizador al grabar", "de": "Timer während der Aufnahme anzeigen", "fr": "Afficher le minuteur pendant l'enregistrement", "pt": "Mostrar temporizador ao gravar", "zh-Hans": "录音时显示计时器", "ja": "録音中にタイマーを表示", "ko": "녹음 중 타이머 표시", "it": "Mostra timer durante la registrazione", "tr": "Kayıt sırasında zamanlayıcıyı göster"],
        "general.sounds": ["en": "Play start/stop sound", "ru": "Звук при старте и остановке", "es": "Reproducir sonido de inicio/parada", "de": "Start-/Stopp-Sound abspielen", "fr": "Jouer un son au début et à la fin", "pt": "Tocar som de início/fim", "zh-Hans": "播放开始/停止提示音", "ja": "開始/停止音を再生", "ko": "시작/중지 소리 재생", "it": "Riproduci suono avvio/stop", "tr": "Başlat/durdur sesi çal"],
        "general.uiLanguage": ["en": "Interface language", "ru": "Язык интерфейса", "es": "Idioma de la interfaz", "de": "Oberflächensprache", "fr": "Langue de l'interface", "pt": "Idioma da interface", "zh-Hans": "界面语言", "ja": "表示言語", "ko": "인터페이스 언어", "it": "Lingua dell'interfaccia", "tr": "Arayüz dili"],
        "insert.paste": ["en": "Paste via clipboard", "ru": "Вставка через буфер", "es": "Pegar con portapapeles", "de": "Über Zwischenablage einfügen", "fr": "Coller via le presse-papiers", "pt": "Colar via área de transferência", "zh-Hans": "通过剪贴板粘贴", "ja": "クリップボードで貼り付け", "ko": "클립보드로 붙여넣기", "it": "Incolla tramite appunti", "tr": "Pano ile yapıştır"],
        "insert.typing": ["en": "Simulated typing (no clipboard)", "ru": "Имитация набора (без буфера)", "es": "Escritura simulada (sin portapapeles)", "de": "Simulierte Eingabe (ohne Zwischenablage)", "fr": "Saisie simulée (sans presse-papiers)", "pt": "Digitação simulada (sem área de transferência)", "zh-Hans": "模拟键入（不用剪贴板）", "ja": "キー入力シミュレート（クリップボードなし）", "ko": "키 입력 시뮬레이션 (클립보드 없음)", "it": "Digitazione simulata (senza appunti)", "tr": "Simüle yazma (panosuz)"],
        "lang.ar": ["en": "Arabic", "ru": "Арабский", "es": "Arabic", "de": "Arabic", "fr": "Arabic", "pt": "Arabic", "zh-Hans": "Arabic", "ja": "Arabic", "ko": "Arabic", "it": "Arabic", "tr": "Arapça"],
        "lang.auto": ["en": "Same as spoken", "ru": "Как в речи", "es": "Same as spoken", "de": "Same as spoken", "fr": "Same as spoken", "pt": "Same as spoken", "zh-Hans": "Same as spoken", "ja": "Same as spoken", "ko": "Same as spoken", "it": "Same as spoken", "tr": "Konuşulan dil ile aynı"],
        "lang.bn": ["en": "Bengali", "ru": "Бенгальский", "es": "Bengali", "de": "Bengali", "fr": "Bengali", "pt": "Bengali", "zh-Hans": "Bengali", "ja": "Bengali", "ko": "Bengali", "it": "Bengali", "tr": "Bengalce"],
        "lang.de": ["en": "German", "ru": "Немецкий", "es": "German", "de": "German", "fr": "German", "pt": "German", "zh-Hans": "German", "ja": "German", "ko": "German", "it": "German", "tr": "Almanca"],
        "lang.en": ["en": "English", "ru": "Английский", "es": "English", "de": "English", "fr": "English", "pt": "English", "zh-Hans": "English", "ja": "English", "ko": "English", "it": "English", "tr": "İngilizce"],
        "lang.es": ["en": "Spanish", "ru": "Испанский", "es": "Spanish", "de": "Spanish", "fr": "Spanish", "pt": "Spanish", "zh-Hans": "Spanish", "ja": "Spanish", "ko": "Spanish", "it": "Spanish", "tr": "İspanyolca"],
        "lang.fr": ["en": "French", "ru": "Французский", "es": "French", "de": "French", "fr": "French", "pt": "French", "zh-Hans": "French", "ja": "French", "ko": "French", "it": "French", "tr": "Fransızca"],
        "lang.hi": ["en": "Hindi", "ru": "Хинди", "es": "Hindi", "de": "Hindi", "fr": "Hindi", "pt": "Hindi", "zh-Hans": "Hindi", "ja": "Hindi", "ko": "Hindi", "it": "Hindi", "tr": "Hintçe"],
        "lang.id": ["en": "Indonesian", "ru": "Индонезийский", "es": "Indonesian", "de": "Indonesian", "fr": "Indonesian", "pt": "Indonesian", "zh-Hans": "Indonesian", "ja": "Indonesian", "ko": "Indonesian", "it": "Indonesian", "tr": "Endonezce"],
        "lang.it": ["en": "Italian", "ru": "Итальянский", "es": "Italian", "de": "Italian", "fr": "Italian", "pt": "Italian", "zh-Hans": "Italian", "ja": "Italian", "ko": "Italian", "it": "Italian", "tr": "İtalyanca"],
        "lang.ja": ["en": "Japanese", "ru": "Японский", "es": "Japanese", "de": "Japanese", "fr": "Japanese", "pt": "Japanese", "zh-Hans": "Japanese", "ja": "Japanese", "ko": "Japanese", "it": "Japanese", "tr": "Japonca"],
        "lang.ko": ["en": "Korean", "ru": "Корейский", "es": "Korean", "de": "Korean", "fr": "Korean", "pt": "Korean", "zh-Hans": "Korean", "ja": "Korean", "ko": "Korean", "it": "Korean", "tr": "Korece"],
        "lang.nl": ["en": "Dutch", "ru": "Нидерландский", "es": "Dutch", "de": "Dutch", "fr": "Dutch", "pt": "Dutch", "zh-Hans": "Dutch", "ja": "Dutch", "ko": "Dutch", "it": "Dutch", "tr": "Felemenkçe"],
        "lang.pl": ["en": "Polish", "ru": "Польский", "es": "Polish", "de": "Polish", "fr": "Polish", "pt": "Polish", "zh-Hans": "Polish", "ja": "Polish", "ko": "Polish", "it": "Polish", "tr": "Lehçe"],
        "lang.pt": ["en": "Portuguese", "ru": "Португальский", "es": "Portuguese", "de": "Portuguese", "fr": "Portuguese", "pt": "Portuguese", "zh-Hans": "Portuguese", "ja": "Portuguese", "ko": "Portuguese", "it": "Portuguese", "tr": "Portekizce"],
        "lang.ru": ["en": "Russian", "ru": "Русский", "es": "Russian", "de": "Russian", "fr": "Russian", "pt": "Russian", "zh-Hans": "Russian", "ja": "Russian", "ko": "Russian", "it": "Russian", "tr": "Rusça"],
        "lang.tr": ["en": "Turkish", "ru": "Турецкий", "es": "Turkish", "de": "Turkish", "fr": "Turkish", "pt": "Turkish", "zh-Hans": "Turkish", "ja": "Turkish", "ko": "Turkish", "it": "Turkish", "tr": "Türkçe"],
        "lang.uk": ["en": "Ukrainian", "ru": "Украинский", "es": "Ukrainian", "de": "Ukrainian", "fr": "Ukrainian", "pt": "Ukrainian", "zh-Hans": "Ukrainian", "ja": "Ukrainian", "ko": "Ukrainian", "it": "Ukrainian", "tr": "Ukraynaca"],
        "lang.vi": ["en": "Vietnamese", "ru": "Вьетнамский", "es": "Vietnamese", "de": "Vietnamese", "fr": "Vietnamese", "pt": "Vietnamese", "zh-Hans": "Vietnamese", "ja": "Vietnamese", "ko": "Vietnamese", "it": "Vietnamese", "tr": "Vietnamca"],
        "lang.zh": ["en": "Chinese (Simplified)", "ru": "Китайский (упрощённый)", "es": "Chinese (Simplified)", "de": "Chinese (Simplified)", "fr": "Chinese (Simplified)", "pt": "Chinese (Simplified)", "zh-Hans": "Chinese (Simplified)", "ja": "Chinese (Simplified)", "ko": "Chinese (Simplified)", "it": "Chinese (Simplified)", "tr": "Çince (Basitleştirilmiş)"],
        "menu.cancel": ["en": "Cancel Dictation", "ru": "Отменить диктовку", "es": "Cancelar dictado", "de": "Diktat abbrechen", "fr": "Annuler la dictée", "pt": "Cancelar ditado", "zh-Hans": "取消听写", "ja": "キャンセル", "ko": "받아쓰기 취소", "it": "Annulla dettatura", "tr": "Dikteyi İptal Et"],
        "menu.provider": ["en": "Current Provider", "ru": "Текущий провайдер", "es": "Proveedor actual", "de": "Aktueller Anbieter", "fr": "Fournisseur actuel", "pt": "Provedor atual", "zh-Hans": "当前服务商", "ja": "現在のプロバイダー", "ko": "현재 제공자", "it": "Provider attuale", "tr": "Geçerli Sağlayıcı"],
        "menu.quit": ["en": "Quit FlowDictate", "ru": "Выйти из FlowDictate", "es": "Salir de FlowDictate", "de": "FlowDictate beenden", "fr": "Quitter FlowDictate", "pt": "Sair do FlowDictate", "zh-Hans": "退出 FlowDictate", "ja": "FlowDictate を終了", "ko": "FlowDictate 종료", "it": "Esci da FlowDictate", "tr": "FlowDictate’ten Çık"],
        "menu.settings": ["en": "Settings…", "ru": "Настройки…", "es": "Ajustes…", "de": "Einstellungen…", "fr": "Réglages…", "pt": "Ajustes…", "zh-Hans": "设置…", "ja": "設定…", "ko": "설정…", "it": "Impostazioni…", "tr": "Ayarlar…"],
        "menu.startStop": ["en": "Start/Stop Dictation", "ru": "Старт/стоп диктовки", "es": "Iniciar/detener dictado", "de": "Diktat starten/stoppen", "fr": "Démarrer/arrêter la dictée", "pt": "Iniciar/parar ditado", "zh-Hans": "开始/停止听写", "ja": "ディクテーション開始/停止", "ko": "받아쓰기 시작/중지", "it": "Avvia/ferma dettatura", "tr": "Dikteyi Başlat/Durdur"],
        "menu.updates": ["en": "Check for Updates…", "ru": "Проверить обновления…", "es": "Buscar actualizaciones…", "de": "Nach Updates suchen…", "fr": "Rechercher des mises à jour…", "pt": "Verificar atualizações…", "zh-Hans": "检查更新…", "ja": "アップデートを確認…", "ko": "업데이트 확인…", "it": "Verifica aggiornamenti…", "tr": "Güncellemeleri Kontrol Et…"],
        "mode.hold": ["en": "Hold to dictate", "ru": "Удерживать для диктовки", "es": "Mantener para dictar", "de": "Halten zum Diktieren", "fr": "Maintenir pour dicter", "pt": "Segurar para ditar", "zh-Hans": "按住听写", "ja": "長押しでディクテーション", "ko": "누르고 받아쓰기", "it": "Tieni premuto per dettare", "tr": "Dikte için basılı tut"],
        "mode.toggle": ["en": "Press once to start, press again to stop", "ru": "Одно нажатие — старт, повторное — стоп", "es": "Pulsa una vez para iniciar, otra para detener", "de": "Einmal drücken zum Starten, erneut zum Stoppen", "fr": "Appuyer une fois pour démarrer, encore pour arrêter", "pt": "Pressione uma vez para iniciar, de novo para parar", "zh-Hans": "按一次开始，再按停止", "ja": "一度で開始、もう一度で停止", "ko": "한 번 시작, 다시 눌러 중지", "it": "Premi una volta per avviare, di nuovo per fermare", "tr": "Başlatmak için bir kez, durdurmak için tekrar bas"],
        "overlay.inserted": ["en": "Inserted", "ru": "Вставлено", "es": "Insertado", "de": "Eingefügt", "fr": "Inséré", "pt": "Inserido", "zh-Hans": "已插入", "ja": "挿入済み", "ko": "삽입됨", "it": "Inserito", "tr": "Eklendi"],
        "overlay.recording": ["en": "Recording", "ru": "Запись", "es": "Grabando", "de": "Aufnahme", "fr": "Enregistrement", "pt": "Gravando", "zh-Hans": "录音中", "ja": "録音中", "ko": "녹음 중", "it": "Registrazione", "tr": "Kayıt"],
        "overlay.transcribing": ["en": "Transcribing…", "ru": "Транскрибация…", "es": "Transcribiendo…", "de": "Transkription…", "fr": "Transcription…", "pt": "Transcrevendo…", "zh-Hans": "转写中…", "ja": "文字起こし中…", "ko": "변환 중…", "it": "Trascrizione…", "tr": "Yazıya dökülüyor…"],
        "perm.allowed": ["en": "Allowed", "ru": "Разрешено", "es": "Permitido", "de": "Erlaubt", "fr": "Autorisé", "pt": "Permitido", "zh-Hans": "已允许", "ja": "許可済み", "ko": "허용됨", "it": "Consentito", "tr": "İzin verildi"],
        "perm.ax": ["en": "Accessibility", "ru": "Универсальный доступ", "es": "Accesibilidad", "de": "Bedienungshilfen", "fr": "Accessibilité", "pt": "Acessibilidade", "zh-Hans": "辅助功能", "ja": "アクセシビリティ", "ko": "손쉬운 사용", "it": "Accessibilità", "tr": "Erişilebilirlik"],
        "perm.axDesc": ["en": "Lets FlowDictate paste or type the transcript into the app you are using.", "ru": "Позволяет вставлять или вводить текст в активное приложение.", "es": "Permite pegar o escribir la transcripción en la app que usas.", "de": "Ermöglicht Einfügen oder Tippen des Transkripts in die aktive App.", "fr": "Permet de coller ou saisir la transcription dans l'app active.", "pt": "Permite colar ou digitar a transcrição no app ativo.", "zh-Hans": "允许将转写结果粘贴或键入到当前应用。", "ja": "使用中のアプリに文字起こしを貼り付けまたは入力します。", "ko": "사용 중인 앱에 받아쓴 내용을 붙여넣거나 입력합니다.", "it": "Consente di incollare o digitare la trascrizione nell'app attiva.", "tr": "Yazıyı kullandığınız uygulamaya yapıştırmayı veya yazmayı sağlar."],
        "perm.denied": ["en": "Denied", "ru": "Запрещено", "es": "Denegado", "de": "Verweigert", "fr": "Refusé", "pt": "Negado", "zh-Hans": "已拒绝", "ja": "拒否", "ko": "거부됨", "it": "Negato", "tr": "Reddedildi"],
        "perm.done": ["en": "Done", "ru": "Готово", "es": "Listo", "de": "Fertig", "fr": "Terminé", "pt": "Concluído", "zh-Hans": "完成", "ja": "完了", "ko": "완료", "it": "Fatto", "tr": "Tamam"],
        "perm.enable": ["en": "Enable %@", "ru": "Включить %@", "es": "Activar %@", "de": "%@ aktivieren", "fr": "Activer %@", "pt": "Ativar %@", "zh-Hans": "启用 %@", "ja": "%@ を有効化", "ko": "%@ 사용", "it": "Abilita %@", "tr": "%@ etkinleştir"],
        "perm.hint1": ["en": "After allowing a permission, return here — status updates automatically.", "ru": "После выдачи разрешения вернитесь сюда — статус обновится сам.", "es": "Tras permitir, vuelve aquí: el estado se actualiza solo.", "de": "Nach der Erlaubnis hierher zurück — Status aktualisiert sich.", "fr": "Après autorisation, revenez ici — le statut se met à jour.", "pt": "Depois de permitir, volte aqui — o status atualiza sozinho.", "zh-Hans": "授权后回到这里，状态会自动更新。", "ja": "許可後に戻ると状態が自動更新されます。", "ko": "허용 후 돌아오면 상태가 자동 갱신됩니다.", "it": "Dopo aver concesso, torna qui: lo stato si aggiorna.", "tr": "İzin verdikten sonra buraya dönün — durum otomatik güncellenir."],
        "perm.hint2": ["en": "If a dialog does not appear, open System Settings with the button and enable FlowDictate.", "ru": "Если диалог не появился — откройте Системные настройки кнопкой и включите FlowDictate.", "es": "Si no aparece el diálogo, abre Ajustes del Sistema y activa FlowDictate.", "de": "Wenn kein Dialog erscheint: Systemeinstellungen öffnen und FlowDictate aktivieren.", "fr": "Si aucun dialogue n'apparaît, ouvrez Réglages Système et activez FlowDictate.", "pt": "Se o diálogo não aparecer, abra Ajustes do Sistema e ative o FlowDictate.", "zh-Hans": "若未弹出对话框，请点按钮打开系统设置并启用 FlowDictate。", "ja": "ダイアログが出ない場合は設定を開き FlowDictate を有効にしてください。", "ko": "대화상자가 없으면 설정에서 FlowDictate를 켜세요.", "it": "Se non compare il dialogo, apri Impostazioni di Sistema e abilita FlowDictate.", "tr": "İletişim kutusu çıkmazsa Sistem Ayarları’nı açıp FlowDictate’i etkinleştirin."],
        "perm.im": ["en": "Input Monitoring", "ru": "Мониторинг ввода", "es": "Monitorización de entrada", "de": "Eingabeüberwachung", "fr": "Surveillance des entrées", "pt": "Monitoramento de entrada", "zh-Hans": "输入监控", "ja": "入力モニタリング", "ko": "입력 모니터링", "it": "Monitoraggio input", "tr": "Giriş İzleme"],
        "perm.imDesc": ["en": "Needed for Right ⌘ / Right ⌥ shortcuts. Use a custom shortcut to skip this.", "ru": "Нужен для Right ⌘ / Right ⌥. Можно выбрать свой шорткат без этого.", "es": "Necesario para Right ⌘ / Right ⌥. Usa un atajo personalizado para omitirlo.", "de": "Für Right ⌘ / Right ⌥ nötig. Eigenes Kürzel umgeht das.", "fr": "Nécessaire pour Right ⌘ / Right ⌥. Un raccourci personnalisé l'évite.", "pt": "Necessário para Right ⌘ / Right ⌥. Use atalho personalizado para pular.", "zh-Hans": "Right ⌘ / Right ⌥ 快捷键需要此项。可用自定义快捷键跳过。", "ja": "Right ⌘ / Right ⌥ に必要。カスタムショートカットなら不要。", "ko": "Right ⌘ / Right ⌥ 에 필요. 사용자 지정 단축키로 생략 가능.", "it": "Serve per Right ⌘ / Right ⌥. Con scorciatoia personalizzata non serve.", "tr": "Sağ ⌘ / Sağ ⌥ için gerekir. Özel kısayol ile atlanabilir."],
        "perm.imNoteOff": ["en": "Custom shortcuts use Carbon hotkeys (no Input Monitoring).", "ru": "Свой шорткат через Carbon (мониторинг ввода не нужен).", "es": "Los atajos personalizados usan Carbon (sin Monitorización).", "de": "Eigene Kürzel nutzen Carbon (keine Eingabeüberwachung).", "fr": "Les raccourcis perso utilisent Carbon (pas de Surveillance).", "pt": "Atalhos personalizados usam Carbon (sem Monitoramento).", "zh-Hans": "自定义快捷键使用 Carbon（无需输入监控）。", "ja": "カスタムショートカットは Carbon 使用（入力モニタリング不要）。", "ko": "사용자 지정 단축키는 Carbon 사용(입력 모니터링 불필요).", "it": "Le scorciatoie personalizzate usano Carbon (senza monitoraggio).", "tr": "Özel kısayollar Carbon kullanır (Giriş İzleme gerekmez)."],
        "perm.imNoteOn": ["en": "Input Monitoring is needed for Right ⌘ / Right ⌥ shortcuts.", "ru": "Мониторинг ввода нужен для Right ⌘ / Right ⌥.", "es": "Monitorización de entrada necesaria para Right ⌘ / Right ⌥.", "de": "Eingabeüberwachung nötig für Right ⌘ / Right ⌥.", "fr": "Surveillance des entrées requise pour Right ⌘ / Right ⌥.", "pt": "Monitoramento de entrada necessário para Right ⌘ / Right ⌥.", "zh-Hans": "Right ⌘ / Right ⌥ 需要输入监控。", "ja": "Right ⌘ / Right ⌥ には入力モニタリングが必要です。", "ko": "Right ⌘ / Right ⌥ 에는 입력 모니터링이 필요합니다.", "it": "Il monitoraggio input serve per Right ⌘ / Right ⌥.", "tr": "Sağ ⌘ / Sağ ⌥ için Giriş İzleme gerekir."],
        "perm.intro": ["en": "FlowDictate only asks for what it needs. Each button opens the native macOS dialog or System Settings.", "ru": "FlowDictate запрашивает только необходимое. Каждая кнопка открывает системный диалог или Настройки.", "es": "FlowDictate solo pide lo necesario. Cada botón abre el diálogo nativo o Ajustes del sistema.", "de": "FlowDictate fragt nur das Nötige an. Jeder Knopf öffnet den Systemdialog oder die Systemeinstellungen.", "fr": "FlowDictate ne demande que le nécessaire. Chaque bouton ouvre le dialogue macOS ou Réglages Système.", "pt": "O FlowDictate pede só o necessário. Cada botão abre o diálogo nativo ou Ajustes do Sistema.", "zh-Hans": "FlowDictate 只请求必要权限。每个按钮会打开系统对话框或系统设置。", "ja": "必要な権限のみ要求します。各ボタンでシステムのダイアログまたは設定を開きます。", "ko": "필요한 권한만 요청합니다. 각 버튼은 시스템 대화상자 또는 설정을 엽니다.", "it": "FlowDictate chiede solo il necessario. Ogni pulsante apre il dialogo di sistema o Impostazioni di Sistema.", "tr": "FlowDictate yalnızca ihtiyacı olanı ister. Her düğme sistem iletişim kutusunu veya Sistem Ayarları’nı açar."],
        "perm.later": ["en": "Later", "ru": "Позже", "es": "Después", "de": "Später", "fr": "Plus tard", "pt": "Depois", "zh-Hans": "稍后", "ja": "後で", "ko": "나중에", "it": "Dopo", "tr": "Sonra"],
        "perm.mic": ["en": "Microphone", "ru": "Микрофон", "es": "Micrófono", "de": "Mikrofon", "fr": "Microphone", "pt": "Microfone", "zh-Hans": "麦克风", "ja": "マイク", "ko": "마이크", "it": "Microfono", "tr": "Mikrofon"],
        "perm.micDesc": ["en": "Records audio only while you are dictating. Never in the background.", "ru": "Записывает звук только во время диктовки. Не в фоне.", "es": "Graba audio solo mientras dictas. Nunca en segundo plano.", "de": "Nimmt nur während des Diktats auf. Nie im Hintergrund.", "fr": "Enregistre uniquement pendant la dictée. Jamais en arrière-plan.", "pt": "Grava áudio só enquanto você dita. Nunca em segundo plano.", "zh-Hans": "仅在听写时录音，不会在后台录音。", "ja": "ディクテーション中のみ録音。バックグラウンドでは録音しません。", "ko": "받아쓰는 동안에만 녹음합니다. 백그라운드에서는 녹음하지 않습니다.", "it": "Registra audio solo durante la dettatura. Mai in background.", "tr": "Yalnızca dikte ederken ses kaydeder. Arka planda asla."],
        "perm.notEnabled": ["en": "Not enabled", "ru": "Не включено", "es": "No activado", "de": "Nicht aktiviert", "fr": "Non activé", "pt": "Não ativado", "zh-Hans": "未启用", "ja": "未有効", "ko": "사용 안 함", "it": "Non abilitato", "tr": "Açık değil"],
        "perm.openFull": ["en": "Open Settings…", "ru": "Открыть настройки…", "es": "Abrir ajustes…", "de": "Einstellungen öffnen…", "fr": "Ouvrir les réglages…", "pt": "Abrir ajustes…", "zh-Hans": "打开设置…", "ja": "設定を開く…", "ko": "설정 열기…", "it": "Apri impostazioni…", "tr": "Ayarları Aç…"],
        "perm.openSettings": ["en": "Open Settings", "ru": "Открыть Настройки", "es": "Abrir Ajustes", "de": "Einstellungen öffnen", "fr": "Ouvrir Réglages", "pt": "Abrir Ajustes", "zh-Hans": "打开设置", "ja": "設定を開く", "ko": "설정 열기", "it": "Apri Impostazioni", "tr": "Ayarları Aç"],
        "perm.optional": ["en": "Optional", "ru": "Необязательно", "es": "Opcional", "de": "Optional", "fr": "Facultatif", "pt": "Opcional", "zh-Hans": "可选", "ja": "任意", "ko": "선택", "it": "Facoltativo", "tr": "İsteğe bağlı"],
        "perm.progress": ["en": "%d of %d enabled", "ru": "%d из %d включено", "es": "%d de %d activados", "de": "%d von %d aktiviert", "fr": "%d sur %d activés", "pt": "%d de %d ativados", "zh-Hans": "已启用 %d / %d", "ja": "%d / %d 有効", "ko": "%d / %d 사용 중", "it": "%d di %d attivi", "tr": "%d / %d etkin"],
        "perm.ready": ["en": "Ready to dictate", "ru": "Готово к диктовке", "es": "Listo para dictar", "de": "Bereit zum Diktieren", "fr": "Prêt à dicter", "pt": "Pronto para ditar", "zh-Hans": "可以听写", "ja": "ディクテーション可能", "ko": "받아쓰기 준비됨", "it": "Pronto per dettare", "tr": "Dikteye hazır"],
        "perm.required": ["en": "Required", "ru": "Обязательно", "es": "Obligatorio", "de": "Erforderlich", "fr": "Obligatoire", "pt": "Obrigatório", "zh-Hans": "必需", "ja": "必須", "ko": "필수", "it": "Obbligatorio", "tr": "Gerekli"],
        "perm.setup": ["en": "Setup needed", "ru": "Нужна настройка", "es": "Configuración necesaria", "de": "Einrichtung erforderlich", "fr": "Configuration requise", "pt": "Configuração necessária", "zh-Hans": "需要设置", "ja": "設定が必要", "ko": "설정 필요", "it": "Configurazione necessaria", "tr": "Kurulum gerekli"],
        "perm.title": ["en": "Permissions", "ru": "Разрешения", "es": "Permisos", "de": "Berechtigungen", "fr": "Autorisations", "pt": "Permissões", "zh-Hans": "权限", "ja": "権限", "ko": "권한", "it": "Autorizzazioni", "tr": "İzinler"],
        "perm.welcome": ["en": "Welcome to FlowDictate", "ru": "Добро пожаловать в FlowDictate", "es": "Bienvenido a FlowDictate", "de": "Willkommen bei FlowDictate", "fr": "Bienvenue dans FlowDictate", "pt": "Bem-vindo ao FlowDictate", "zh-Hans": "欢迎使用 FlowDictate", "ja": "FlowDictate へようこそ", "ko": "FlowDictate에 오신 것을 환영합니다", "it": "Benvenuto in FlowDictate", "tr": "FlowDictate’e hoş geldiniz"],
        "perm.welcomeBody": ["en": "Enable a couple of macOS permissions so dictation can record and insert text.", "ru": "Включите несколько разрешений macOS, чтобы диктовка могла записывать и вставлять текст.", "es": "Activa unos permisos de macOS para grabar e insertar texto.", "de": "Aktiviere ein paar macOS-Berechtigungen zum Aufnehmen und Einfügen.", "fr": "Activez quelques autorisations macOS pour enregistrer et insérer du texte.", "pt": "Ative algumas permissões do macOS para gravar e inserir texto.", "zh-Hans": "启用几项 macOS 权限以便录音并插入文字。", "ja": "録音と挿入のために macOS の権限を有効にしてください。", "ko": "녹음과 삽입을 위해 macOS 권한을 켜 주세요.", "it": "Abilita alcune autorizzazioni macOS per registrare e inserire testo.", "tr": "Kayıt ve metin ekleme için birkaç macOS iznini açın."],
        "pos.bottomCenter": ["en": "Bottom center", "ru": "Снизу по центру", "es": "Abajo centro", "de": "Unten Mitte", "fr": "Bas centre", "pt": "Inferior centro", "zh-Hans": "底部居中", "ja": "下中央", "ko": "하단 중앙", "it": "Basso centro", "tr": "Alt orta"],
        "pos.bottomLeft": ["en": "Bottom left", "ru": "Снизу слева", "es": "Abajo izquierda", "de": "Unten links", "fr": "Bas gauche", "pt": "Inferior esquerda", "zh-Hans": "左下", "ja": "左下", "ko": "왼쪽 아래", "it": "Basso sinistra", "tr": "Alt sol"],
        "pos.bottomRight": ["en": "Bottom right", "ru": "Снизу справа", "es": "Abajo derecha", "de": "Unten rechts", "fr": "Bas droite", "pt": "Inferior direita", "zh-Hans": "右下", "ja": "右下", "ko": "오른쪽 아래", "it": "Basso destra", "tr": "Alt sağ"],
        "pos.topCenter": ["en": "Top center", "ru": "Сверху по центру", "es": "Arriba centro", "de": "Oben Mitte", "fr": "Haut centre", "pt": "Superior centro", "zh-Hans": "顶部居中", "ja": "上中央", "ko": "상단 중앙", "it": "Alto centro", "tr": "Üst orta"],
        "pos.topLeft": ["en": "Top left", "ru": "Сверху слева", "es": "Arriba izquierda", "de": "Oben links", "fr": "Haut gauche", "pt": "Superior esquerda", "zh-Hans": "左上", "ja": "左上", "ko": "왼쪽 위", "it": "Alto sinistra", "tr": "Üst sol"],
        "pos.topRight": ["en": "Top right", "ru": "Сверху справа", "es": "Arriba derecha", "de": "Oben rechts", "fr": "Haut droite", "pt": "Superior direita", "zh-Hans": "右上", "ja": "右上", "ko": "오른쪽 위", "it": "Alto destra", "tr": "Üst sağ"],
        "preset.custom": ["en": "Custom shortcut", "ru": "Свой шорткат", "es": "Atajo personalizado", "de": "Benutzerdefiniertes Kürzel", "fr": "Raccourci personnalisé", "pt": "Atalho personalizado", "zh-Hans": "自定义快捷键", "ja": "カスタムショートカット", "ko": "사용자 지정 단축키", "it": "Scorciatoia personalizzata", "tr": "Özel kısayol"],
        "preset.rightCommand": ["en": "Right Command", "ru": "Правый Command", "es": "Command derecho", "de": "Rechte Command-Taste", "fr": "Commande droite", "pt": "Command direito", "zh-Hans": "右 Command", "ja": "右 Command", "ko": "오른쪽 Command", "it": "Command destro", "tr": "Sağ Command"],
        "preset.rightOption": ["en": "Right Option", "ru": "Правый Option", "es": "Option derecho", "de": "Rechte Option-Taste", "fr": "Option droite", "pt": "Option direito", "zh-Hans": "右 Option", "ja": "右 Option", "ko": "오른쪽 Option", "it": "Option destro", "tr": "Sağ Option"],
        "prov.apiKey": ["en": "API key", "ru": "API-ключ", "es": "Clave API", "de": "API-Schlüssel", "fr": "Clé API", "pt": "Chave API", "zh-Hans": "API 密钥", "ja": "API キー", "ko": "API 키", "it": "Chiave API", "tr": "API anahtarı"],
        "prov.baseURL": ["en": "Base URL", "ru": "Базовый URL", "es": "URL base", "de": "Basis-URL", "fr": "URL de base", "pt": "URL base", "zh-Hans": "基础 URL", "ja": "ベース URL", "ko": "기본 URL", "it": "URL di base", "tr": "Temel URL"],
        "prov.clear": ["en": "Clear key", "ru": "Очистить ключ", "es": "Borrar clave", "de": "Schlüssel löschen", "fr": "Effacer la clé", "pt": "Limpar chave", "zh-Hans": "清除密钥", "ja": "キーを消去", "ko": "키 지우기", "it": "Cancella chiave", "tr": "Anahtarı sil"],
        "prov.codeSwitch": ["en": "Code switching", "ru": "Переключение языков", "es": "Cambio de código", "de": "Code-Switching", "fr": "Alternance codique", "pt": "Alternância de código", "zh-Hans": "语码转换", "ja": "コードスイッチング", "ko": "코드 전환", "it": "Code switching", "tr": "Kod değiştirme"],
        "prov.enhPunct": ["en": "Enhanced punctuation", "ru": "Улучшенная пунктуация", "es": "Puntuación mejorada", "de": "Erweiterte Zeichensetzung", "fr": "Ponctuation améliorée", "pt": "Pontuação aprimorada", "zh-Hans": "增强标点", "ja": "強化句読点", "ko": "향상된 문장 부호", "it": "Punteggiatura avanzata", "tr": "Gelişmiş noktalama"],
        "prov.model": ["en": "Model", "ru": "Модель", "es": "Modelo", "de": "Modell", "fr": "Modèle", "pt": "Modelo", "zh-Hans": "模型", "ja": "モデル", "ko": "모델", "it": "Modello", "tr": "Model"],
        "prov.notConfigured": ["en": "Status: Not configured", "ru": "Статус: не настроено", "es": "Estado: No configurado", "de": "Status: Nicht konfiguriert", "fr": "État : Non configuré", "pt": "Status: Não configurado", "zh-Hans": "状态：未配置", "ja": "状態: 未設定", "ko": "상태: 구성되지 않음", "it": "Stato: Non configurato", "tr": "Durum: Yapılandırılmadı"],
        "prov.numerals": ["en": "Numerals", "ru": "Числа", "es": "Números", "de": "Ziffern", "fr": "Chiffres", "pt": "Numerais", "zh-Hans": "数字", "ja": "数字", "ko": "숫자", "it": "Numeri", "tr": "Sayılar"],
        "prov.provider": ["en": "Provider", "ru": "Провайдер", "es": "Proveedor", "de": "Anbieter", "fr": "Fournisseur", "pt": "Provedor", "zh-Hans": "服务商", "ja": "プロバイダー", "ko": "제공자", "it": "Provider", "tr": "Sağlayıcı"],
        "prov.punct": ["en": "Punctuation", "ru": "Пунктуация", "es": "Puntuación", "de": "Zeichensetzung", "fr": "Ponctuation", "pt": "Pontuação", "zh-Hans": "标点", "ja": "句読点", "ko": "문장 부호", "it": "Punteggiatura", "tr": "Noktalama"],
        "prov.ready": ["en": "Status: Ready", "ru": "Статус: готово", "es": "Estado: Listo", "de": "Status: Bereit", "fr": "État : Prêt", "pt": "Status: Pronto", "zh-Hans": "状态：就绪", "ja": "状態: 準備完了", "ko": "상태: 준비됨", "it": "Stato: Pronto", "tr": "Durum: Hazır"],
        "prov.reload": ["en": "Reload from Keychain", "ru": "Загрузить из Связки ключей", "es": "Recargar del Llavero", "de": "Aus Schlüsselbund laden", "fr": "Recharger depuis le Trousseau", "pt": "Recarregar do Porta-chaves", "zh-Hans": "从钥匙串重新加载", "ja": "キーチェーンから再読込", "ko": "키체인에서 다시 로드", "it": "Ricarica dal Portachiavi", "tr": "Keychain’den yükle"],
        "prov.save": ["en": "Save key", "ru": "Сохранить ключ", "es": "Guardar clave", "de": "Schlüssel speichern", "fr": "Enregistrer la clé", "pt": "Salvar chave", "zh-Hans": "保存密钥", "ja": "キーを保存", "ko": "키 저장", "it": "Salva chiave", "tr": "Anahtarı kaydet"],
        "prov.saved": ["en": "Status: Saved to Keychain", "ru": "Статус: сохранено в Связке ключей", "es": "Estado: Guardado en Llavero", "de": "Status: Im Schlüsselbund gespeichert", "fr": "État : Enregistré dans le Trousseau", "pt": "Status: Salvo no Porta-chaves", "zh-Hans": "状态：已保存到钥匙串", "ja": "状態: キーチェーンに保存済み", "ko": "상태: 키체인에 저장됨", "it": "Stato: Salvato nel Portachiavi", "tr": "Durum: Keychain’e kaydedildi"],
        "prov.smartFmt": ["en": "Smart formatting", "ru": "Умное форматирование", "es": "Formato inteligente", "de": "Intelligente Formatierung", "fr": "Mise en forme intelligente", "pt": "Formatação inteligente", "zh-Hans": "智能格式", "ja": "スマート書式", "ko": "스마트 서식", "it": "Formattazione smart", "tr": "Akıllı biçimlendirme"],
        "section.advanced": ["en": "Advanced", "ru": "Дополнительно", "es": "Avanzado", "de": "Erweitert", "fr": "Avancé", "pt": "Avançado", "zh-Hans": "高级", "ja": "詳細", "ko": "고급", "it": "Avanzate", "tr": "Gelişmiş"],
        "section.dictation": ["en": "Dictation", "ru": "Диктовка", "es": "Dictado", "de": "Diktat", "fr": "Dictée", "pt": "Ditado", "zh-Hans": "听写", "ja": "ディクテーション", "ko": "받아쓰기", "it": "Dettatura", "tr": "Dikte"],
        "section.general": ["en": "General", "ru": "Основное", "es": "General", "de": "Allgemein", "fr": "Général", "pt": "Geral", "zh-Hans": "通用", "ja": "一般", "ko": "일반", "it": "Generale", "tr": "Genel"],
        "section.permissions": ["en": "Permissions", "ru": "Разрешения", "es": "Permisos", "de": "Berechtigungen", "fr": "Autorisations", "pt": "Permissões", "zh-Hans": "权限", "ja": "権限", "ko": "권한", "it": "Autorizzazioni", "tr": "İzinler"],
        "section.providers": ["en": "Providers", "ru": "Провайдеры", "es": "Proveedores", "de": "Anbieter", "fr": "Fournisseurs", "pt": "Provedores", "zh-Hans": "服务商", "ja": "プロバイダー", "ko": "제공자", "it": "Provider", "tr": "Sağlayıcılar"],
        "section.updates": ["en": "Updates", "ru": "Обновления", "es": "Actualizaciones", "de": "Updates", "fr": "Mises à jour", "pt": "Atualizações", "zh-Hans": "更新", "ja": "アップデート", "ko": "업데이트", "it": "Aggiornamenti", "tr": "Güncellemeler"],
        "upd.check": ["en": "Check for updates", "ru": "Проверить обновления", "es": "Buscar actualizaciones", "de": "Nach Updates suchen", "fr": "Rechercher des mises à jour", "pt": "Verificar atualizações", "zh-Hans": "检查更新", "ja": "アップデートを確認", "ko": "업데이트 확인", "it": "Verifica aggiornamenti", "tr": "Güncellemeleri kontrol et"],
        "upd.checkOnLaunch": ["en": "Check for updates on launch", "ru": "Проверять обновления при запуске", "es": "Buscar actualizaciones al iniciar", "de": "Beim Start nach Updates suchen", "fr": "Vérifier les mises à jour au lancement", "pt": "Verificar atualizações ao iniciar", "zh-Hans": "启动时检查更新", "ja": "起動時にアップデートを確認", "ko": "시작 시 업데이트 확인", "it": "Controlla aggiornamenti all'avvio", "tr": "Açılışta güncellemeleri kontrol et"],
        "upd.checking": ["en": "Checking…", "ru": "Проверка…", "es": "Buscando…", "de": "Suche…", "fr": "Recherche…", "pt": "Verificando…", "zh-Hans": "检查中…", "ja": "確認中…", "ko": "확인 중…", "it": "Controllo…", "tr": "Kontrol ediliyor…"],
        "upd.openDownload": ["en": "Open download", "ru": "Открыть загрузку", "es": "Abrir descarga", "de": "Download öffnen", "fr": "Ouvrir le téléchargement", "pt": "Abrir download", "zh-Hans": "打开下载", "ja": "ダウンロードを開く", "ko": "다운로드 열기", "it": "Apri download", "tr": "İndirmeyi aç"],
        "upd.prereleases": ["en": "Include pre-releases", "ru": "Включать пре-релизы", "es": "Incluir prelanzamientos", "de": "Vorabversionen einbeziehen", "fr": "Inclure les préversions", "pt": "Incluir pré-lançamentos", "zh-Hans": "包含预发布版", "ja": "プレリリースを含める", "ko": "사전 출시 포함", "it": "Includi pre-release", "tr": "Ön sürümleri dahil et"],
    ]
}
