import Foundation
/// App UI language + string table. Every user-visible string should go through `L10n.t`.
enum AppUILanguage: String, CaseIterable, Identifiable {
    case system = "system"
    case en = "en"
    case ru = "ru"
    case es = "es"
    case de = "de"
    case fr = "fr"
    case pt = "pt"
    case zhHans = "zh-Hans"
    case ja = "ja"
    case ko = "ko"
    case it = "it"
    case tr = "tr"
    var id: String { rawValue }
    var displayName: String {
        switch self {
        case .system: return L10n.t("appearance.system")
        case .en: return "English"
        case .ru: return "Русский"
        case .es: return "Español"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .pt: return "Português"
        case .zhHans: return "简体中文"
        case .ja: return "日本語"
        case .ko: return "한국어"
        case .it: return "Italiano"
        case .tr: return "Türkçe"
        }
    }
    var resolvedCode: String {
        if self != .system { return rawValue }
        let preferred = Locale.preferredLanguages.first ?? "en"
        let code = Locale(identifier: preferred).language.languageCode?.identifier ?? "en"
        switch code {
        case "ru": return "ru"
        case "es": return "es"
        case "de": return "de"
        case "fr": return "fr"
        case "pt": return "pt"
        case "zh": return "zh-Hans"
        case "ja": return "ja"
        case "ko": return "ko"
        case "it": return "it"
        case "tr": return "tr"
        default: return "en"
        }
    }
}

enum L10n {
    nonisolated(unsafe) static var code: String = "en"

    static func t(_ key: String) -> String {
        if let row = table[key] {
            return row[code] ?? row["en"] ?? key
        }
        return key
    }

    static func tf(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: Locale(identifier: code), arguments: args)
    }

    private static let table: [String: [String: String]] = [
        "adv.clearKeys": ["en": "Clear all API keys", "ru": "Удалить все API-ключи", "es": "Borrar todas las claves API", "de": "Alle API-Schlüssel löschen", "fr": "Effacer toutes les clés API", "pt": "Limpar todas as chaves API", "zh-Hans": "清除所有 API 密钥", "ja": "すべての API キーを消去", "ko": "모든 API 키 지우기", "it": "Cancella tutte le chiavi API", "tr": "Tüm API anahtarlarını sil"],
        "adv.clearLog": ["en": "Clear diagnostics log", "ru": "Очистить лог диагностики", "es": "Borrar registro de diagnóstico", "de": "Diagnoseprotokoll löschen", "fr": "Effacer le journal de diagnostic", "pt": "Limpar log de diagnóstico", "zh-Hans": "清除诊断日志", "ja": "診断ログを消去", "ko": "진단 로그 지우기", "it": "Cancella log di diagnostica", "tr": "Tanılama günlüğünü temizle"],
        "adv.debugHint": ["en": "Keeps temporary WAV files after each dictation for debugging.", "ru": "Не удаляет временные WAV после диктовки (для отладки).", "es": "Conserva los archivos WAV temporales después de cada dictado para depuración.", "de": "Behält temporäre WAV-Dateien nach jedem Diktat zur Fehlerdiagnose.", "fr": "Conserve les fichiers WAV temporaires après chaque dictée pour le débogage.", "pt": "Mantém os arquivos WAV temporários após cada ditado para depuração.", "zh-Hans": "保留每次听写后的临时 WAV 文件以便调试。", "ja": "デバッグ用に、各ディクテーション後の一時 WAV ファイルを保持します。", "ko": "디버깅을 위해 받아쓰기 후 임시 WAV 파일을 보관합니다.", "it": "Conserva i file WAV temporanei dopo ogni dettatura per il debug.", "tr": "Hata ayıklama için her dikteden sonra geçici WAV dosyalarını tutar."],
        "dict.cancelHint": ["en": "Press Escape while recording or transcribing to cancel.", "ru": "Escape во время записи или распознавания — отмена.", "es": "Pulsa Escape durante la grabación o transcripción para cancelar.", "de": "Drücke während der Aufnahme oder Transkription Escape, um abzubrechen.", "fr": "Appuyez sur Échap pendant l’enregistrement ou la transcription pour annuler.", "pt": "Pressione Escape durante a gravação ou transcrição para cancelar.", "zh-Hans": "录音或转写时按 Escape 可取消。", "ja": "録音または文字起こし中に Escape を押すとキャンセルします。", "ko": "녹음 또는 변환 중 Escape를 누르면 취소됩니다.", "it": "Premi Escape durante la registrazione o la trascrizione per annullare.", "tr": "Kayıt veya yazıya dökme sırasında iptal etmek için Escape’e basın."],
        "hist.clear": ["en": "Clear history", "ru": "Очистить историю", "es": "Borrar historial", "de": "Verlauf löschen", "fr": "Effacer l’historique", "pt": "Limpar histórico", "zh-Hans": "清除历史记录", "ja": "履歴を消去", "ko": "기록 지우기", "it": "Cancella cronologia", "tr": "Geçmişi temizle"],
        "hist.copy": ["en": "Copy", "ru": "Копировать", "es": "Copiar", "de": "Kopieren", "fr": "Copier", "pt": "Copiar", "zh-Hans": "复制", "ja": "コピー", "ko": "복사", "it": "Copia", "tr": "Kopyala"],
        "hist.delete": ["en": "Delete", "ru": "Удалить", "es": "Eliminar", "de": "Löschen", "fr": "Supprimer", "pt": "Excluir", "zh-Hans": "删除", "ja": "削除", "ko": "삭제", "it": "Elimina", "tr": "Sil"],
        "hist.empty": ["en": "No transcripts yet. Dictate something — it will show up here if history is on.", "ru": "Пока пусто. Сдиктуйте текст — он появится здесь, если история включена.", "es": "Aún no hay transcripciones. Dicta algo y aparecerá aquí si el historial está activado.", "de": "Noch keine Transkripte. Diktiere etwas – bei aktiviertem Verlauf erscheint es hier.", "fr": "Aucune transcription pour le moment. Dictez quelque chose : le texte apparaîtra ici si l’historique est activé.", "pt": "Ainda não há transcrições. Dite algo e o texto aparecerá aqui se o histórico estiver ativado.", "zh-Hans": "还没有转写记录。进行一次听写；若已开启历史记录，文本会显示在这里。", "ja": "文字起こし履歴はまだありません。履歴が有効なら、ディクテーションした内容がここに表示されます。", "ko": "아직 변환 기록이 없습니다. 기록이 켜져 있으면 받아쓴 내용이 여기에 표시됩니다.", "it": "Non ci sono ancora trascrizioni. Detta qualcosa: apparirà qui se la cronologia è attiva.", "tr": "Henüz metin yok. Bir şey dikte edin; geçmiş açıksa burada görünür."],
        "hist.save": ["en": "Save recent transcripts on this Mac", "ru": "Сохранять недавние тексты на этом Mac", "es": "Guardar transcripciones recientes en este Mac", "de": "Letzte Transkripte auf diesem Mac speichern", "fr": "Enregistrer les transcriptions récentes sur ce Mac", "pt": "Salvar transcrições recentes neste Mac", "zh-Hans": "在这台 Mac 上保存最近的转写", "ja": "最近の文字起こしをこの Mac に保存", "ko": "최근 변환 내용을 이 Mac에 저장", "it": "Salva le trascrizioni recenti su questo Mac", "tr": "Son metinleri bu Mac’te kaydet"],
        "hist.saveHint": ["en": "Local only. Last 30 items. Never uploaded by Dictabar.", "ru": "Только локально. Последние 30. Dictabar никуда не отправляет.", "es": "Solo local. Últimos 30 elementos. Dictabar nunca los sube.", "de": "Nur lokal. Die letzten 30 Einträge. Dictabar lädt sie niemals hoch.", "fr": "Uniquement en local. 30 derniers éléments. Dictabar ne les envoie jamais.", "pt": "Somente local. Últimos 30 itens. O Dictabar nunca os envia.", "zh-Hans": "仅保存在本地，最多 30 条。Dictabar 绝不会上传。", "ja": "ローカルのみ。直近 30 件。Dictabar がアップロードすることはありません。", "ko": "로컬에만 최근 30개를 저장합니다. Dictabar는 업로드하지 않습니다.", "it": "Solo in locale. Ultimi 30 elementi. Dictabar non li carica mai.", "tr": "Yalnızca yerel. Son 30 öğe. Dictabar bunları asla yüklemez."],
        "hist.settings": ["en": "History", "ru": "История", "es": "Historial", "de": "Verlauf", "fr": "Historique", "pt": "Histórico", "zh-Hans": "历史记录", "ja": "履歴", "ko": "기록", "it": "Cronologia", "tr": "Geçmiş"],
        "local.chooseCloud": ["en": "Choose cloud provider…", "ru": "Выбрать облачный провайдер…", "es": "Elegir proveedor en la nube…", "de": "Cloud-Anbieter wählen…", "fr": "Choisir un fournisseur cloud…", "pt": "Escolher provedor de nuvem…", "zh-Hans": "选择云服务商…", "ja": "クラウドプロバイダーを選択…", "ko": "클라우드 제공자 선택…", "it": "Scegli provider cloud…", "tr": "Bulut sağlayıcısı seç…"],
        "local.download": ["en": "Download", "ru": "Скачать", "es": "Descargar", "de": "Laden", "fr": "Télécharger", "pt": "Baixar", "zh-Hans": "下载", "ja": "ダウンロード", "ko": "다운로드", "it": "Scarica", "tr": "İndir"],
        "local.downloadedUnloaded": ["en": "Downloaded · not in memory", "ru": "Скачана · не загружена в память", "es": "Descargado · fuera de memoria", "de": "Geladen · nicht im Speicher", "fr": "Téléchargé · hors mémoire", "pt": "Baixado · fora da memória", "zh-Hans": "已下载 · 未载入内存", "ja": "ダウンロード済み · メモリ未読込", "ko": "다운로드됨 · 메모리에서 해제됨", "it": "Scaricato · non in memoria", "tr": "İndirildi · bellekte değil"],
        "local.inMemory": ["en": "In memory · active", "ru": "В памяти · активна", "es": "En memoria · activo", "de": "Im Speicher · aktiv", "fr": "En mémoire · actif", "pt": "Na memória · ativo", "zh-Hans": "内存中 · 已启用", "ja": "メモリ内 · 使用中", "ko": "메모리 내 · 활성", "it": "In memoria · attivo", "tr": "Bellekte · etkin"],
        "local.installed": ["en": "Downloaded", "ru": "Скачана", "es": "Descargado", "de": "Geladen", "fr": "Téléchargé", "pt": "Baixado", "zh-Hans": "已下载", "ja": "ダウンロード済み", "ko": "다운로드됨", "it": "Scaricato", "tr": "İndirildi"],
        "local.loading": ["en": "Loading into memory…", "ru": "Загружается в память…", "es": "Cargando en memoria…", "de": "Wird in den Speicher geladen…", "fr": "Chargement en mémoire…", "pt": "Carregando na memória…", "zh-Hans": "正在载入内存…", "ja": "メモリに読み込み中…", "ko": "메모리에 로드 중…", "it": "Caricamento in memoria…", "tr": "Belleğe yükleniyor…"],
        "local.manage": ["en": "Manage local models…", "ru": "Управление локальными моделями…", "es": "Gestionar modelos locales…", "de": "Lokale Modelle verwalten…", "fr": "Gérer les modèles locaux…", "pt": "Gerenciar modelos locais…", "zh-Hans": "管理本地模型…", "ja": "ローカルモデルを管理…", "ko": "로컬 모델 관리…", "it": "Gestisci modelli locali…", "tr": "Yerel modelleri yönet…"],
        "local.memoryPolicy": ["en": "Use selects a model; it loads only for dictation. Only one local model can stay in memory. Choosing another local model or any cloud provider unloads it automatically.", "ru": "«Использовать» выбирает модель; в память она загружается только для диктовки. В памяти может быть только одна локальная модель. Выбор другой локальной модели или любого облачного провайдера автоматически выгружает её.", "es": "Usar selecciona un modelo; solo se carga al dictar. Solo puede haber un modelo local en memoria. Elegir otro modelo local o cualquier proveedor en la nube lo descarga automáticamente.", "de": "Verwenden wählt ein Modell; es wird erst beim Diktieren geladen. Nur ein lokales Modell bleibt im Speicher. Ein anderes lokales Modell oder ein Cloud-Anbieter entlädt es automatisch.", "fr": "Utiliser sélectionne un modèle ; il n’est chargé que pour la dictée. Un seul modèle local peut rester en mémoire. Un autre modèle local ou fournisseur cloud le décharge automatiquement.", "pt": "Usar seleciona um modelo; ele só é carregado ao ditar. Apenas um modelo local pode ficar na memória. Outro modelo local ou provedor de nuvem o descarrega automaticamente.", "zh-Hans": "“使用”会选择模型；仅在听写时载入。内存中只能保留一个本地模型。选择其他本地模型或任意云服务商时会自动卸载。", "ja": "「使用」でモデルを選択し、音声入力時だけ読み込みます。メモリに保持できるローカルモデルは1つです。別のローカルモデルやクラウドプロバイダーを選ぶと自動的に解放されます。", "ko": "사용을 누르면 모델이 선택되며 받아쓰기할 때만 로드됩니다. 메모리에는 로컬 모델 하나만 유지됩니다. 다른 로컬 모델이나 클라우드 제공자를 선택하면 자동으로 해제됩니다.", "it": "Usa seleziona un modello, che viene caricato solo durante la dettatura. In memoria può restare un solo modello locale. Un altro modello locale o un provider cloud lo scarica automaticamente.", "tr": "Kullan modeli seçer; model yalnızca dikte sırasında yüklenir. Bellekte yalnızca bir yerel model kalabilir. Başka bir yerel model veya bulut sağlayıcısı seçmek modeli otomatik olarak bellekten çıkarır."],
        "local.moss": ["en": "Long recordings with speaker labels · 50+ languages.", "ru": "Длинные записи с разделением по спикерам · 50+ языков.", "es": "Grabaciones largas con etiquetas de hablante · más de 50 idiomas.", "de": "Lange Aufnahmen mit Sprecherkennzeichnung · über 50 Sprachen.", "fr": "Longs enregistrements avec identification des locuteurs · plus de 50 langues.", "pt": "Gravações longas com identificação de falantes · mais de 50 idiomas.", "zh-Hans": "长录音与说话人标注 · 50多种语言。", "ja": "長時間録音と話者ラベル · 50以上の言語。", "ko": "장시간 녹음 및 화자 구분 · 50개 이상의 언어.", "it": "Registrazioni lunghe con etichette dei parlanti · oltre 50 lingue.", "tr": "Konuşmacı etiketli uzun kayıtlar · 50'den fazla dil."],
        "local.nemotron": ["en": "Streaming transcription with punctuation · 35 languages.", "ru": "Потоковое распознавание с пунктуацией · 35 языков.", "es": "Transcripción en streaming con puntuación · 35 idiomas.", "de": "Streaming-Transkription mit Satzzeichen · 35 Sprachen.", "fr": "Transcription en continu avec ponctuation · 35 langues.", "pt": "Transcrição em streaming com pontuação · 35 idiomas.", "zh-Hans": "带标点的流式转写 · 35种语言。", "ja": "句読点付きストリーミング文字起こし · 35言語。", "ko": "문장 부호가 포함된 스트리밍 전사 · 35개 언어.", "it": "Trascrizione in streaming con punteggiatura · 35 lingue.", "tr": "Noktalama işaretli akış transkripsiyonu · 35 dil."],
        "local.notInstalled": ["en": "Not downloaded", "ru": "Не скачана", "es": "No descargado", "de": "Nicht geladen", "fr": "Non téléchargé", "pt": "Não baixado", "zh-Hans": "未下载", "ja": "未ダウンロード", "ko": "다운로드되지 않음", "it": "Non scaricato", "tr": "İndirilmedi"],
        "local.parakeet": ["en": "Low-latency dictation · 25 languages.", "ru": "Диктовка с низкой задержкой · 25 языков.", "es": "Dictado de baja latencia · 25 idiomas.", "de": "Diktat mit geringer Latenz · 25 Sprachen.", "fr": "Dictée à faible latence · 25 langues.", "pt": "Ditado de baixa latência · 25 idiomas.", "zh-Hans": "低延迟听写 · 25种语言。", "ja": "低遅延の音声入力 · 25言語。", "ko": "저지연 받아쓰기 · 25개 언어.", "it": "Dettatura a bassa latenza · 25 lingue.", "tr": "Düşük gecikmeli dikte · 25 dil."],
        "local.preparing": ["en": "Preparing download…", "ru": "Подготовка загрузки…", "es": "Preparando descarga…", "de": "Download wird vorbereitet…", "fr": "Préparation du téléchargement…", "pt": "Preparando download…", "zh-Hans": "正在准备下载…", "ja": "ダウンロードを準備中…", "ko": "다운로드 준비 중…", "it": "Preparazione del download…", "tr": "İndirme hazırlanıyor…"],
        "local.privacy": ["en": "Models are downloaded once from Hugging Face. Transcription then runs entirely on this Mac; audio is never uploaded.", "ru": "Модель один раз скачивается с Hugging Face. После этого распознавание полностью работает на этом Mac; аудио никуда не загружается.", "es": "Los modelos se descargan una vez desde Hugging Face. Después, la transcripción se realiza por completo en este Mac; el audio nunca se sube.", "de": "Modelle werden einmal von Hugging Face geladen. Danach läuft die Transkription vollständig auf diesem Mac; Audio wird nie hochgeladen.", "fr": "Les modèles sont téléchargés une fois depuis Hugging Face. La transcription s’effectue ensuite entièrement sur ce Mac ; l’audio n’est jamais envoyé.", "pt": "Os modelos são baixados uma vez do Hugging Face. Depois, a transcrição ocorre inteiramente neste Mac; o áudio nunca é enviado.", "zh-Hans": "模型仅从 Hugging Face 下载一次。之后转写完全在这台 Mac 上运行；音频绝不会上传。", "ja": "モデルは Hugging Face から一度だけダウンロードされます。その後の文字起こしはすべてこのMac上で行われ、音声がアップロードされることはありません。", "ko": "모델은 Hugging Face에서 한 번만 다운로드됩니다. 이후 전사는 이 Mac에서만 실행되며 오디오는 업로드되지 않습니다.", "it": "I modelli vengono scaricati una sola volta da Hugging Face. La trascrizione avviene poi interamente su questo Mac; l'audio non viene mai caricato.", "tr": "Modeller Hugging Face'den bir kez indirilir. Ardından transkripsiyon tamamen bu Mac'te çalışır; ses asla yüklenmez."],
        "local.qwen": ["en": "Speech and song transcription · 30 languages and 22 dialects.", "ru": "Распознавание речи и песен · 30 языков и 22 диалекта.", "es": "Transcripción de voz y canciones · 30 idiomas y 22 dialectos.", "de": "Sprach- und Liedtranskription · 30 Sprachen und 22 Dialekte.", "fr": "Transcription de parole et de chansons · 30 langues et 22 dialectes.", "pt": "Transcrição de fala e música · 30 idiomas e 22 dialetos.", "zh-Hans": "语音与歌曲转写 · 30种语言和22种方言。", "ja": "音声と歌の文字起こし · 30言語と22方言。", "ko": "음성 및 노래 전사 · 30개 언어와 22개 방언.", "it": "Trascrizione di voce e canzoni · 30 lingue e 22 dialetti.", "tr": "Konuşma ve şarkı transkripsiyonu · 30 dil ve 22 lehçe."],
        "local.remove": ["en": "Remove", "ru": "Удалить", "es": "Eliminar", "de": "Entfernen", "fr": "Supprimer", "pt": "Remover", "zh-Hans": "移除", "ja": "削除", "ko": "제거", "it": "Rimuovi", "tr": "Kaldır"],
        "local.selected": ["en": "Selected", "ru": "Выбрана", "es": "Seleccionado", "de": "Ausgewählt", "fr": "Sélectionné", "pt": "Selecionado", "zh-Hans": "已选择", "ja": "選択済み", "ko": "선택됨", "it": "Selezionato", "tr": "Seçildi"],
        "local.selectedLazy": ["en": "Selected · loads on first dictation", "ru": "Выбрана · загрузится при первой диктовке", "es": "Seleccionado · se carga al primer dictado", "de": "Ausgewählt · lädt beim ersten Diktat", "fr": "Sélectionné · chargé à la première dictée", "pt": "Selecionado · carrega no primeiro ditado", "zh-Hans": "已选择 · 首次听写时载入", "ja": "選択済み · 初回の音声入力時に読み込み", "ko": "선택됨 · 첫 받아쓰기 시 로드", "it": "Selezionato · si carica alla prima dettatura", "tr": "Seçildi · ilk diktede yüklenir"],
        "local.selectedProvider": ["en": "Local transcription: %@", "ru": "Локальное распознавание: %@", "es": "Transcripción local: %@", "de": "Lokale Transkription: %@", "fr": "Transcription locale : %@", "pt": "Transcrição local: %@", "zh-Hans": "本地转写：%@", "ja": "ローカル文字起こし：%@", "ko": "로컬 전사: %@", "it": "Trascrizione locale: %@", "tr": "Yerel transkripsiyon: %@"],
        "local.unload": ["en": "Unload from memory", "ru": "Выгрузить из памяти", "es": "Descargar de la memoria", "de": "Aus Speicher entladen", "fr": "Décharger de la mémoire", "pt": "Descarregar da memória", "zh-Hans": "从内存卸载", "ja": "メモリから解放", "ko": "메모리에서 해제", "it": "Scarica dalla memoria", "tr": "Bellekten çıkar"],
        "local.use": ["en": "Use", "ru": "Использовать", "es": "Usar", "de": "Verwenden", "fr": "Utiliser", "pt": "Usar", "zh-Hans": "使用", "ja": "使用", "ko": "사용", "it": "Usa", "tr": "Kullan"],
        "prov.group.free": ["en": "Free & trial · easy setup", "ru": "Бесплатно и trial · просто", "es": "Gratis y prueba · configuración fácil", "de": "Kostenlos & Test · einfache Einrichtung", "fr": "Gratuit et essai · configuration simple", "pt": "Grátis e teste · configuração fácil", "zh-Hans": "免费与试用 · 轻松设置", "ja": "無料・トライアル · 簡単設定", "ko": "무료 및 체험판 · 간편 설정", "it": "Gratis e prova · configurazione semplice", "tr": "Ücretsiz ve deneme · kolay kurulum"],
        "prov.group.local": ["en": "On-device", "ru": "На устройстве", "es": "En el dispositivo", "de": "Auf dem Gerät", "fr": "Sur l’appareil", "pt": "No dispositivo", "zh-Hans": "设备端", "ja": "デバイス上", "ko": "기기 내", "it": "Sul dispositivo", "tr": "Cihazda"],
        "prov.group.paid": ["en": "Paid · simple API key", "ru": "Платные · простой API-ключ", "es": "De pago · clave API sencilla", "de": "Kostenpflichtig · einfacher API-Schlüssel", "fr": "Payant · clé API simple", "pt": "Pago · chave de API simples", "zh-Hans": "付费 · 简单 API 密钥", "ja": "有料 · シンプルなAPIキー", "ko": "유료 · 간단한 API 키", "it": "A pagamento · chiave API semplice", "tr": "Ücretli · basit API anahtarı"],
        "prov.group.routers": ["en": "Aggregators & custom", "ru": "Агрегаторы и custom", "es": "Agregadores y personalizados", "de": "Aggregatoren & benutzerdefiniert", "fr": "Agrégateurs et personnalisés", "pt": "Agregadores e personalizados", "zh-Hans": "聚合器与自定义", "ja": "アグリゲーター・カスタム", "ko": "통합 및 사용자 지정", "it": "Aggregatori e personalizzati", "tr": "Toplayıcılar ve özel"],
        "prov.group.cloud": ["en": "Cloud platforms · advanced", "ru": "Облака · сложная настройка", "es": "Plataformas en la nube · avanzado", "de": "Cloud-Plattformen · erweitert", "fr": "Plateformes cloud · avancé", "pt": "Plataformas de nuvem · avançado", "zh-Hans": "云平台 · 高级", "ja": "クラウドプラットフォーム · 上級", "ko": "클라우드 플랫폼 · 고급", "it": "Piattaforme cloud · avanzato", "tr": "Bulut platformları · gelişmiş"],
        "prov.test": ["en": "Test connection", "ru": "Проверить соединение", "es": "Probar conexión", "de": "Verbindung testen", "fr": "Tester la connexion", "pt": "Testar conexão", "zh-Hans": "测试连接", "ja": "接続をテスト", "ko": "연결 테스트", "it": "Verifica connessione", "tr": "Bağlantıyı test et"],
        "quick.freeHint": ["en": "These have free/trial quotas. Full list (paid, routers, cloud) is in Settings → Providers.", "ru": "У этих есть free/trial. Полный список (платные, агрегаторы, облака) — в Настройки → Провайдеры.", "es": "Tienen cuotas gratis o de prueba. La lista completa está en Ajustes → Proveedores.", "de": "Diese bieten Gratis- oder Testkontingente. Die vollständige Liste steht unter Einstellungen → Anbieter.", "fr": "Ils proposent des quotas gratuits ou d’essai. La liste complète est dans Réglages → Fournisseurs.", "pt": "Eles têm cotas gratuitas ou de teste. A lista completa está em Ajustes → Provedores.", "zh-Hans": "这些服务提供免费或试用额度。完整列表位于“设置 → 服务商”。", "ja": "無料またはトライアル枠があります。全一覧は「設定 → プロバイダー」にあります。", "ko": "무료 또는 체험 할당량이 있습니다. 전체 목록은 설정 → 제공자에서 확인하세요.", "it": "Offrono quote gratuite o di prova. L’elenco completo è in Impostazioni → Provider.", "tr": "Ücretsiz veya deneme kotaları vardır. Tam liste Ayarlar → Sağlayıcılar bölümündedir."],
        "prov.testEmptyOK": ["en": "(empty transcript — silence is OK)", "ru": "(пустой текст — тишина нормальна)", "es": "(transcripción vacía: el silencio es válido)", "de": "(leeres Transkript – Stille ist in Ordnung)", "fr": "(transcription vide : le silence est normal)", "pt": "(transcrição vazia: silêncio é aceitável)", "zh-Hans": "（空转写：静音属于正常情况）", "ja": "（文字起こしなし：無音なら正常です）", "ko": "(빈 전사 — 무음은 정상입니다)", "it": "(trascrizione vuota: il silenzio è normale)", "tr": "(boş transkripsiyon — sessizlik normaldir)"],
        "prov.testFail": ["en": "Failed: %@", "ru": "Ошибка: %@", "es": "Error: %@", "de": "Fehlgeschlagen: %@", "fr": "Échec : %@", "pt": "Falha: %@", "zh-Hans": "失败：%@", "ja": "失敗：%@", "ko": "실패: %@", "it": "Errore: %@", "tr": "Başarısız: %@"],
        "prov.testOK": ["en": "OK · %@", "ru": "OK · %@", "es": "Correcto · %@", "de": "OK · %@", "fr": "OK · %@", "pt": "OK · %@", "zh-Hans": "正常 · %@", "ja": "OK · %@", "ko": "정상 · %@", "it": "OK · %@", "tr": "Tamam · %@"],
        "prov.testing": ["en": "Testing…", "ru": "Проверка…", "es": "Probando…", "de": "Wird getestet…", "fr": "Test en cours…", "pt": "Testando…", "zh-Hans": "正在测试…", "ja": "テスト中…", "ko": "테스트 중…", "it": "Verifica in corso…", "tr": "Test ediliyor…"],
        "quick.body": ["en": "Start with a free/trial provider and paste your API key. Audio goes only there.", "ru": "Начните с free/trial провайдера и вставьте API-ключ. Аудио уходит только ему.", "es": "Empieza con un proveedor gratis o de prueba y pega tu clave API. El audio solo se envía allí.", "de": "Beginne mit einem Gratis- oder Testanbieter und füge deinen API-Schlüssel ein. Audio geht nur dorthin.", "fr": "Commencez avec un fournisseur gratuit ou d’essai et collez votre clé API. L’audio lui est uniquement envoyé.", "pt": "Comece com um provedor gratuito ou de teste e cole sua chave de API. O áudio só é enviado para ele.", "zh-Hans": "先选择免费或试用服务商，然后粘贴 API 密钥。音频只会发送给该服务商。", "ja": "無料またはトライアルのプロバイダーを選び、APIキーを貼り付けます。音声はそこにだけ送信されます。", "ko": "무료 또는 체험 제공자를 선택하고 API 키를 붙여 넣으세요. 오디오는 해당 제공자에게만 전송됩니다.", "it": "Inizia con un provider gratuito o di prova e incolla la chiave API. L’audio viene inviato solo lì.", "tr": "Ücretsiz veya deneme sağlayıcısıyla başlayın ve API anahtarınızı yapıştırın. Ses yalnızca oraya gönderilir."],
        "quick.moreProviders": ["en": "All providers…", "ru": "Все провайдеры…", "es": "Todos los proveedores…", "de": "Alle Anbieter…", "fr": "Tous les fournisseurs…", "pt": "Todos os provedores…", "zh-Hans": "所有服务商…", "ja": "すべてのプロバイダー…", "ko": "모든 제공자…", "it": "Tutti i provider…", "tr": "Tüm sağlayıcılar…"],
        "quick.privacy": ["en": "Keys stay in a private file on this Mac. No Dictabar account.", "ru": "Ключи хранятся в приватном файле на этом Mac. Аккаунта Dictabar нет.", "es": "Las claves se guardan en un archivo privado en este Mac. No hay cuenta de Dictabar.", "de": "Schlüssel bleiben in einer privaten Datei auf diesem Mac. Kein Dictabar-Konto.", "fr": "Les clés restent dans un fichier privé sur ce Mac. Aucun compte Dictabar.", "pt": "As chaves ficam em um arquivo privado neste Mac. Sem conta Dictabar.", "zh-Hans": "密钥保存在这台 Mac 的私有文件中。无需 Dictabar 账户。", "ja": "キーはこのMacの非公開ファイルに保存されます。Dictabarアカウントは不要です。", "ko": "키는 이 Mac의 비공개 파일에 보관됩니다. Dictabar 계정은 필요 없습니다.", "it": "Le chiavi restano in un file privato su questo Mac. Nessun account Dictabar.", "tr": "Anahtarlar bu Mac'teki özel bir dosyada kalır. Dictabar hesabı yoktur."],
        "quick.saveContinue": ["en": "Save & continue", "ru": "Сохранить и далее", "es": "Guardar y continuar", "de": "Speichern & weiter", "fr": "Enregistrer et continuer", "pt": "Salvar e continuar", "zh-Hans": "保存并继续", "ja": "保存して続ける", "ko": "저장 후 계속", "it": "Salva e continua", "tr": "Kaydet ve devam et"],
        "quick.skip": ["en": "Skip for now", "ru": "Позже", "es": "Omitir por ahora", "de": "Vorerst überspringen", "fr": "Ignorer pour l’instant", "pt": "Pular por enquanto", "zh-Hans": "暂时跳过", "ja": "今はスキップ", "ko": "지금은 건너뛰기", "it": "Salta per ora", "tr": "Şimdilik atla"],
        "quick.title": ["en": "Set up dictation", "ru": "Настройка диктовки", "es": "Configurar dictado", "de": "Diktat einrichten", "fr": "Configurer la dictée", "pt": "Configurar ditado", "zh-Hans": "设置听写", "ja": "音声入力を設定", "ko": "받아쓰기 설정", "it": "Configura dettatura", "tr": "Dikteyi ayarla"],
        "quit.activeBody": ["en": "Recording or transcription is still running. Quit cancels it.", "ru": "Идёт запись или распознавание. Выход отменит.", "es": "La grabación o transcripción sigue activa. Salir la cancelará.", "de": "Aufnahme oder Transkription läuft noch. Beenden bricht sie ab.", "fr": "L’enregistrement ou la transcription est toujours en cours. Quitter l’annulera.", "pt": "A gravação ou transcrição ainda está em andamento. Sair irá cancelá-la.", "zh-Hans": "录音或转写仍在进行。退出将取消任务。", "ja": "録音または文字起こしが進行中です。終了するとキャンセルされます。", "ko": "녹음 또는 전사가 진행 중입니다. 종료하면 취소됩니다.", "it": "La registrazione o trascrizione è ancora in corso. Uscire la annullerà.", "tr": "Kayıt veya transkripsiyon sürüyor. Çıkmak işlemi iptal eder."],
        "quit.activeTitle": ["en": "Dictation is active", "ru": "Диктовка активна", "es": "El dictado está activo", "de": "Diktat ist aktiv", "fr": "La dictée est active", "pt": "O ditado está ativo", "zh-Hans": "听写正在进行", "ja": "音声入力中", "ko": "받아쓰기 활성", "it": "La dettatura è attiva", "tr": "Dikte etkin"],
        "quit.quitAnyway": ["en": "Quit", "ru": "Выйти", "es": "Salir", "de": "Beenden", "fr": "Quitter", "pt": "Sair", "zh-Hans": "退出", "ja": "終了", "ko": "종료", "it": "Esci", "tr": "Çık"],
        "quit.stay": ["en": "Stay", "ru": "Остаться", "es": "Quedarse", "de": "Bleiben", "fr": "Rester", "pt": "Ficar", "zh-Hans": "留下", "ja": "続ける", "ko": "계속 사용", "it": "Resta", "tr": "Kal"],
        "section.history": ["en": "History", "ru": "История", "es": "Historial", "de": "Verlauf", "fr": "Historique", "pt": "Histórico", "zh-Hans": "历史记录", "ja": "履歴", "ko": "기록", "it": "Cronologia", "tr": "Geçmiş"],
        "section.localModels": ["en": "Local Models", "ru": "Локальные модели", "es": "Modelos locales", "de": "Lokale Modelle", "fr": "Modèles locaux", "pt": "Modelos locais", "zh-Hans": "本地模型", "ja": "ローカルモデル", "ko": "로컬 모델", "it": "Modelli locali", "tr": "Yerel Modeller"],
        "upd.feedHint": ["en": "Updates are delivered securely by Sparkle.", "ru": "Обновления безопасно устанавливаются через Sparkle.", "es": "Las actualizaciones se entregan de forma segura mediante Sparkle.", "de": "Updates werden sicher über Sparkle bereitgestellt.", "fr": "Les mises à jour sont distribuées de manière sécurisée via Sparkle.", "pt": "As atualizações são fornecidas com segurança pelo Sparkle.", "zh-Hans": "更新通过 Sparkle 安全提供。", "ja": "アップデートはSparkleにより安全に配信されます。", "ko": "업데이트는 Sparkle을 통해 안전하게 제공됩니다.", "it": "Gli aggiornamenti vengono distribuiti in sicurezza tramite Sparkle.", "tr": "Güncellemeler Sparkle ile güvenli şekilde sunulur."],
        "adv.debug": ["en": "Debug mode (keep audio files after transcription)", "ru": "Режим отладки (хранить аудио после транскрибации)", "es": "Modo depuración (conservar audio tras transcribir)", "de": "Debug-Modus (Audiodateien behalten)", "fr": "Mode debug (garder les fichiers audio)", "pt": "Modo debug (manter áudio após transcrição)", "zh-Hans": "调试模式（转写后保留音频）", "ja": "デバッグ（文字起こし後も音声を保持）", "ko": "디버그(변환 후 오디오 유지)", "it": "Modalità debug (mantieni audio dopo trascrizione)", "tr": "Hata ayıklama (yazıya dökmeden sonra ses dosyalarını tut)"],
        "adv.exportLog": ["en": "Export diagnostics log", "ru": "Экспорт лога диагностики", "es": "Exportar registro de diagnóstico", "de": "Diagnoseprotokoll exportieren", "fr": "Exporter le journal de diagnostic", "pt": "Exportar log de diagnóstico", "zh-Hans": "导出诊断日志", "ja": "診断ログを書き出す", "ko": "진단 로그 내보내기", "it": "Esporta log di diagnostica", "tr": "Tanılama günlüğünü dışa aktar"],
        "adv.lastError": ["en": "Last error", "ru": "Последняя ошибка", "es": "Último error", "de": "Letzter Fehler", "fr": "Dernière erreur", "pt": "Último erro", "zh-Hans": "上次错误", "ja": "最後のエラー", "ko": "마지막 오류", "it": "Ultimo errore", "tr": "Son hata"],
        "adv.none": ["en": "None", "ru": "Нет", "es": "Ninguno", "de": "Keiner", "fr": "Aucun", "pt": "Nenhum", "zh-Hans": "无", "ja": "なし", "ko": "없음", "it": "Nessuno", "tr": "Yok"],
        "adv.privacy": ["en": "Privacy: Audio goes only to the selected provider. Keys stay in a private local file. Recordings are deleted unless Debug is on.", "ru": "Конфиденциальность: аудио только выбранному провайдеру. Ключи хранятся в приватном локальном файле. Записи удаляются, если Debug выкл.", "es": "Privacidad: audio solo al proveedor elegido. Claves en un archivo local privado. Las grabaciones se borran salvo en depuración.", "de": "Datenschutz: Audio nur an den gewählten Anbieter. Schlüssel liegen in einer privaten lokalen Datei. Aufnahmen werden außer im Debug-Modus gelöscht.", "fr": "Confidentialité : audio uniquement au fournisseur choisi. Clés dans un fichier local privé. Enregistrements supprimés sauf en debug.", "pt": "Privacidade: áudio só para o provedor escolhido. Chaves em arquivo local privado. Gravações apagadas salvo em debug.", "zh-Hans": "隐私：音频仅发送给所选服务商。密钥保存在私有本地文件中。未开启调试时删除录音。", "ja": "プライバシー: 音声は選択したプロバイダーのみへ。キーは非公開のローカルファイルに保存。デバッグ時以外は録音を削除。", "ko": "개인정보: 오디오는 선택한 제공자에게만 전송. 키는 비공개 로컬 파일에 저장. 디버그 외에는 녹음 삭제.", "it": "Privacy: audio solo al provider scelto. Chiavi in un file locale privato. Registrazioni eliminate salvo debug.", "tr": "Gizlilik: Ses yalnızca seçilen sağlayıcıya gider. Anahtarlar özel yerel dosyada kalır. Hata ayıklama dışında kayıtlar silinir."],
        "adv.reset": ["en": "Reset all settings", "ru": "Сбросить все настройки", "es": "Restablecer todos los ajustes", "de": "Alle Einstellungen zurücksetzen", "fr": "Réinitialiser tous les réglages", "pt": "Redefinir todas as configurações", "zh-Hans": "重置所有设置", "ja": "すべての設定をリセット", "ko": "모든 설정 초기화", "it": "Reimposta tutte le impostazioni", "tr": "Tüm ayarları sıfırla"],
        "adv.resetDone": ["en": "Settings reset to defaults.", "ru": "Настройки сброшены к значениям по умолчанию.", "es": "Ajustes restablecidos a los valores predeterminados.", "de": "Einstellungen auf Standard zurückgesetzt.", "fr": "Réglages réinitialisés par défaut.", "pt": "Configurações redefinidas para o padrão.", "zh-Hans": "设置已重置为默认值。", "ja": "設定をデフォルトにリセットしました。", "ko": "설정이 기본값으로 초기화되었습니다.", "it": "Impostazioni ripristinate ai valori predefiniti.", "tr": "Ayarlar varsayılana sıfırlandı."],
        "appearance.dark": ["en": "Dark", "ru": "Тёмная", "es": "Oscura", "de": "Dunkel", "fr": "Sombre", "pt": "Escura", "zh-Hans": "深色", "ja": "ダーク", "ko": "다크", "it": "Scura", "tr": "Koyu"],
        "appearance.light": ["en": "Light", "ru": "Светлая", "es": "Clara", "de": "Hell", "fr": "Claire", "pt": "Clara", "zh-Hans": "浅色", "ja": "ライト", "ko": "라이트", "it": "Chiara", "tr": "Açık"],
        "appearance.system": ["en": "System", "ru": "Системная", "es": "Sistema", "de": "System", "fr": "Système", "pt": "Sistema", "zh-Hans": "系统", "ja": "システム", "ko": "시스템", "it": "Sistema", "tr": "Sistem"],
        "dict.autoInsert": ["en": "Insert into active app automatically", "ru": "Автоматически вставлять в активное приложение", "es": "Insertar automáticamente en la app activa", "de": "Automatisch in die aktive App einfügen", "fr": "Insérer automatiquement dans l'app active", "pt": "Inserir automaticamente no app ativo", "zh-Hans": "自动插入到当前应用", "ja": "アクティブなアプリに自動挿入", "ko": "활성 앱에 자동 삽입", "it": "Inserisci automaticamente nell'app attiva", "tr": "Etkin uygulamaya otomatik ekle"],
        "dict.autoInsertOff": ["en": "Auto-insert is off: transcript is only copied to the clipboard.", "ru": "Авто-вставка выкл.: текст только копируется в буфер.", "es": "Inserción auto desactivada: solo se copia al portapapeles.", "de": "Auto-Einfügen aus: nur Zwischenablage.", "fr": "Insertion auto désactivée : copie uniquement.", "pt": "Inserção auto desligada: só copia.", "zh-Hans": "自动插入已关：仅复制到剪贴板。", "ja": "自動挿入オフ：クリップボードのみ。", "ko": "자동 삽입 꺼짐: 클립보드에만 복사.", "it": "Inserimento auto disattivo: solo appunti.", "tr": "Otomatik ekleme kapalı: metin yalnızca panoya kopyalanır."],
        "dict.cancelWhile": ["en": "Cancel while active", "ru": "Отмена во время работы", "es": "Cancelar mientras está activo", "de": "Abbrechen während aktiv", "fr": "Annuler pendant l'activité", "pt": "Cancelar enquanto ativo", "zh-Hans": "活动时取消", "ja": "動作中にキャンセル", "ko": "활성 중 취소", "it": "Annulla mentre attivo", "tr": "Etkin iken iptal"],
        "dict.clipboardRestore": ["en": "Restore previous clipboard after paste", "ru": "Восстановить прежний буфер после вставки", "es": "Restaurar portapapeles anterior tras pegar", "de": "Vorherige Zwischenablage nach Einfügen wiederherstellen", "fr": "Restaurer l'ancien presse-papiers après collage", "pt": "Restaurar área de transferência anterior após colar", "zh-Hans": "粘贴后恢复原先的剪贴板", "ja": "ペースト後に以前のクリップボードを復元", "ko": "붙여넣기 후 이전 클립보드 복원", "it": "Ripristina appunti precedenti dopo l'incolla", "tr": "Yapıştırdıktan sonra önceki panoyu geri yükle"],
        "dict.clipboardRestoreHintOff": ["en": "The transcript stays on the clipboard after paste.", "ru": "После вставки транскрипт остаётся в буфере обмена.", "es": "La transcripción permanece en el portapapeles.", "de": "Das Transkript bleibt in der Zwischenablage.", "fr": "La transcription reste dans le presse-papiers.", "pt": "A transcrição permanece na área de transferência.", "zh-Hans": "粘贴后转写内容仍留在剪贴板。", "ja": "貼り付け後も文字起こしがクリップボードに残ります。", "ko": "붙여넣기 후에도 받아쓴 내용이 클립보드에 남습니다.", "it": "La trascrizione resta negli appunti dopo l'incolla.", "tr": "Yapıştırmadan sonra yazıya dökülen metin panoda kalır."],
        "dict.clipboardRestoreHintOn": ["en": "The transcript is pasted into the app, then removed from the clipboard and replaced with what was there before.", "ru": "Текст вставляется в приложение, затем удаляется из буфера и возвращается то, что было раньше.", "es": "Se pega la transcripción y luego se elimina del portapapeles, restaurando el contenido anterior.", "de": "Transkript wird eingefügt, dann aus der Zwischenablage entfernt und der alte Inhalt wiederhergestellt.", "fr": "Le texte est collé, puis retiré du presse-papiers ; l'ancien contenu est restauré.", "pt": "A transcrição é colada e depois removida da área de transferência; o conteúdo anterior volta.", "zh-Hans": "转写内容粘贴到应用后，会从剪贴板删除并恢复之前的内容。", "ja": "文字起こしを貼り付けた後、クリップボードから削除し以前の内容に戻します。", "ko": "받아쓴 내용을 붙여넣은 뒤 클립보드에서 제거하고 이전 내용을 복원합니다.", "it": "La trascrizione viene incollata, poi rimossa dagli appunti e sostituita con il contenuto precedente.", "tr": "Metin uygulamaya yapıştırılır, ardından panodan silinir ve önceki pano içeriği geri gelir."],
        "dict.copyOnFail": ["en": "Copy to clipboard if insertion fails", "ru": "Копировать в буфер, если вставка не удалась", "es": "Copiar al portapapeles si falla la inserción", "de": "In Zwischenablage kopieren bei Fehler", "fr": "Copier dans le presse-papiers en cas d'échec", "pt": "Copiar se a inserção falhar", "zh-Hans": "插入失败时复制到剪贴板", "ja": "挿入失敗時はクリップボードへ", "ko": "삽입 실패 시 클립보드에 복사", "it": "Copia negli appunti se l'inserimento fallisce", "tr": "Ekleme başarısız olursa panoya kopyala"],
        "dict.customShortcut": ["en": "Custom shortcut", "ru": "Свой шорткат", "es": "Atajo personalizado", "de": "Benutzerdefiniert", "fr": "Raccourci personnalisé", "pt": "Atalho personalizado", "zh-Hans": "自定义快捷键", "ja": "カスタムショートカット", "ko": "사용자 지정 단축키", "it": "Scorciatoia personalizzata", "tr": "Özel kısayol"],
        "dict.defaultMic": ["en": "System default input", "ru": "Системный микрофон по умолчанию", "es": "Entrada predeterminada del sistema", "de": "Systemstandard-Eingabe", "fr": "Entrée par défaut du système", "pt": "Entrada padrão do sistema", "zh-Hans": "系统默认输入", "ja": "システムのデフォルト入力", "ko": "시스템 기본 입력", "it": "Ingresso predefinito di sistema", "tr": "Sistem varsayılan girişi"],
        "dict.input": ["en": "Input", "ru": "Вход", "es": "Entrada", "de": "Eingabe", "fr": "Entrée", "pt": "Entrada", "zh-Hans": "输入", "ja": "入力", "ko": "입력", "it": "Ingresso", "tr": "Giriş"],
        "dict.insertMethod": ["en": "Insertion method", "ru": "Способ вставки", "es": "Método de inserción", "de": "Einfügemethode", "fr": "Méthode d'insertion", "pt": "Método de inserção", "zh-Hans": "插入方式", "ja": "挿入方法", "ko": "삽입 방법", "it": "Metodo di inserimento", "tr": "Ekleme yöntemi"],
        "dict.insertion": ["en": "Text insertion", "ru": "Вставка текста", "es": "Inserción de texto", "de": "Texteinfügung", "fr": "Insertion de texte", "pt": "Inserção de texto", "zh-Hans": "文本插入", "ja": "テキスト挿入", "ko": "텍스트 삽입", "it": "Inserimento testo", "tr": "Metin ekleme"],
        "dict.maxDuration": ["en": "Maximum recording duration", "ru": "Максимальная длительность записи", "es": "Duración máxima de grabación", "de": "Maximale Aufnahmedauer", "fr": "Durée maximale d'enregistrement", "pt": "Duração máxima de gravação", "zh-Hans": "最长录音时长", "ja": "最長録音時間", "ko": "최대 녹음 시간", "it": "Durata massima registrazione", "tr": "Maksimum kayıt süresi"],
        "dict.maxSec": ["en": "Maximum: %d sec", "ru": "Максимум: %d с", "es": "Máximo: %d s", "de": "Maximum: %d s", "fr": "Maximum : %d s", "pt": "Máximo: %d s", "zh-Hans": "最长：%d 秒", "ja": "最長: %d 秒", "ko": "최대: %d초", "it": "Massimo: %d s", "tr": "Maksimum: %d sn"],
        "dict.mic": ["en": "Microphone", "ru": "Микрофон", "es": "Micrófono", "de": "Mikrofon", "fr": "Microphone", "pt": "Microfone", "zh-Hans": "麦克风", "ja": "マイク", "ko": "마이크", "it": "Microfono", "tr": "Mikrofon"],
        "dict.minDuration": ["en": "Minimum recording duration", "ru": "Минимальная длительность записи", "es": "Duración mínima de grabación", "de": "Minimale Aufnahmedauer", "fr": "Durée minimale d'enregistrement", "pt": "Duração mínima de gravação", "zh-Hans": "最短录音时长", "ja": "最短録音時間", "ko": "최소 녹음 시간", "it": "Durata minima registrazione", "tr": "Minimum kayıt süresi"],
        "dict.minSec": ["en": "Minimum: %.1f sec", "ru": "Минимум: %.1f с", "es": "Mínimo: %.1f s", "de": "Minimum: %.1f s", "fr": "Minimum : %.1f s", "pt": "Mínimo: %.1f s", "zh-Hans": "最短：%.1f 秒", "ja": "最短: %.1f 秒", "ko": "최소: %.1f초", "it": "Minimo: %.1f s", "tr": "Minimum: %.1f sn"],
        "dict.modeHold": ["en": "Hold to record; release to transcribe.", "ru": "Удерживайте для записи; отпустите для транскрибации.", "es": "Mantén pulsado para grabar; suelta para transcribir.", "de": "Halten zum Aufnehmen; loslassen zum Transkribieren.", "fr": "Maintenez pour enregistrer ; relâchez pour transcrire.", "pt": "Segure para gravar; solte para transcrever.", "zh-Hans": "按住录音；松开转写。", "ja": "長押しで録音、離すと文字起こし。", "ko": "누르고 있으면 녹음, 놓으면 변환.", "it": "Tieni premuto per registrare; rilascia per trascrivere.", "tr": "Kayıt için basılı tut; bırakınca yazıya dök."],
        "dict.modeToggle": ["en": "Press once to start; press again to stop and transcribe.", "ru": "Одно нажатие — старт; повторное — стоп и транскрибация.", "es": "Pulsa una vez para iniciar; otra para detener y transcribir.", "de": "Einmal drücken zum Starten; erneut zum Stoppen und Transkribieren.", "fr": "Appuyez une fois pour démarrer ; encore pour arrêter et transcrire.", "pt": "Pressione uma vez para iniciar; de novo para parar e transcrever.", "zh-Hans": "按一次开始；再按停止并转写。", "ja": "一度押して開始、もう一度で停止して文字起こし。", "ko": "한 번 눌러 시작, 다시 눌러 중지 후 변환.", "it": "Premi una volta per avviare; di nuovo per fermare e trascrivere.", "tr": "Başlatmak için bir kez bas; durdurmak ve yazıya dökmek için tekrar bas."],
        "dict.mute": ["en": "Mute system audio while recording", "ru": "Отключать звук системы во время записи", "es": "Silenciar audio del sistema al grabar", "de": "Systemton während Aufnahme stummschalten", "fr": "Couper le son système pendant l'enregistrement", "pt": "Silenciar áudio do sistema ao gravar", "zh-Hans": "录音时静音系统音频", "ja": "録音中はシステム音声をミュート", "ko": "녹음 중 시스템 오디오 음소거", "it": "Silenzia audio di sistema durante la registrazione", "tr": "Kayıt sırasında sistem sesini kapat"],
        "dict.needsIM": ["en": "Requires Input Monitoring in Privacy settings.", "ru": "Нужен доступ «Мониторинг ввода» в настройках конфиденциальности.", "es": "Requiere Monitorización de entrada en Privacidad.", "de": "Erfordert Eingabeüberwachung in den Datenschutzeinstellungen.", "fr": "Nécessite Surveillance des entrées dans Confidentialité.", "pt": "Requer Monitoramento de entrada em Privacidade.", "zh-Hans": "需要在隐私设置中开启“输入监控”。", "ja": "プライバシー設定で入力モニタリングが必要です。", "ko": "개인 정보 보호 설정에서 입력 모니터링이 필요합니다.", "it": "Richiede Monitoraggio input nelle impostazioni Privacy.", "tr": "Gizlilik ayarlarında Giriş İzleme gerekir."],
        "dict.outputLang": ["en": "Output language", "ru": "Язык распознавания", "es": "Idioma de salida", "de": "Ausgabesprache", "fr": "Langue de sortie", "pt": "Idioma de saída", "zh-Hans": "识别语言", "ja": "出力言語", "ko": "출력 언어", "it": "Lingua di output", "tr": "Çıktı dili"],
        "dict.pressShortcut": ["en": "Press shortcut… (Esc to cancel)", "ru": "Нажмите сочетание… (Esc — отмена)", "es": "Pulsa el atajo… (Esc para cancelar)", "de": "Kürzel drücken… (Esc zum Abbrechen)", "fr": "Appuyez sur le raccourci… (Esc pour annuler)", "pt": "Pressione o atalho… (Esc para cancelar)", "zh-Hans": "按下快捷键…（Esc 取消）", "ja": "ショートカットを押す…（Escでキャンセル）", "ko": "단축키를 누르세요… (Esc로 취소)", "it": "Premi scorciatoia… (Esc per annullare)", "tr": "Kısayola bas… (Esc iptal)"],
        "dict.refreshMics": ["en": "Refresh microphones", "ru": "Обновить список микрофонов", "es": "Actualizar micrófonos", "de": "Mikrofone aktualisieren", "fr": "Actualiser les microphones", "pt": "Atualizar microfones", "zh-Hans": "刷新麦克风", "ja": "マイクを更新", "ko": "마이크 새로고침", "it": "Aggiorna microfoni", "tr": "Mikrofonları yenile"],
        "dict.shortcut": ["en": "Shortcut", "ru": "Шорткат", "es": "Atajo", "de": "Tastenkürzel", "fr": "Raccourci", "pt": "Atalho", "zh-Hans": "快捷键", "ja": "ショートカット", "ko": "단축키", "it": "Scorciatoia", "tr": "Kısayol"],
        "dict.shortcutMode": ["en": "Shortcut mode", "ru": "Режим шортката", "es": "Modo del atajo", "de": "Kürzelmodus", "fr": "Mode du raccourci", "pt": "Modo do atalho", "zh-Hans": "快捷键模式", "ja": "ショートカットモード", "ko": "단축키 모드", "it": "Modalità scorciatoia", "tr": "Kısayol modu"],
        "dict.shortcutTrigger": ["en": "Shortcut trigger", "ru": "Триггер шортката", "es": "Activador del atajo", "de": "Auslöser", "fr": "Déclencheur", "pt": "Acionador", "zh-Hans": "触发方式", "ja": "トリガー", "ko": "트리거", "it": "Attivazione", "tr": "Kısayol tetikleyici"],
        "dict.trailingNewline": ["en": "Add trailing newline", "ru": "Добавлять перенос строки в конце", "es": "Añadir salto de línea final", "de": "Zeilenumbruch am Ende", "fr": "Ajouter un saut de ligne final", "pt": "Adicionar nova linha no final", "zh-Hans": "末尾添加换行", "ja": "末尾に改行を追加", "ko": "끝에 줄바꿈 추가", "it": "Aggiungi nuova riga finale", "tr": "Sona satır sonu ekle"],
        "dict.trailingSpace": ["en": "Add trailing space", "ru": "Добавлять пробел в конце", "es": "Añadir espacio final", "de": "Leerzeichen am Ende", "fr": "Ajouter un espace final", "pt": "Adicionar espaço no final", "zh-Hans": "末尾添加空格", "ja": "末尾にスペースを追加", "ko": "끝에 공백 추가", "it": "Aggiungi spazio finale", "tr": "Sona boşluk ekle"],
        "error.accessibility": ["en": "Accessibility permission is required to insert text.", "ru": "Для вставки текста нужен Универсальный доступ.", "es": "Se requiere Accesibilidad para insertar texto.", "de": "Bedienungshilfen sind zum Einfügen erforderlich.", "fr": "L'accessibilité est requise pour insérer du texte.", "pt": "É necessária Acessibilidade para inserir texto.", "zh-Hans": "插入文字需要辅助功能权限。", "ja": "テキスト挿入にはアクセシビリティが必要です。", "ko": "텍스트 삽입에는 손쉬운 사용 권한이 필요합니다.", "it": "Serve Accessibilità per inserire testo.", "tr": "Metin eklemek için Erişilebilirlik izni gerekir."],
        "error.eventSource": ["en": "Could not create a keyboard event source for typing.", "ru": "Не удалось создать источник клавиатурных событий.", "es": "No se pudo crear el origen de eventos de teclado.", "de": "Tastatur-Ereignisquelle konnte nicht erstellt werden.", "fr": "Impossible de créer la source d'événements clavier.", "pt": "Não foi possível criar a fonte de eventos do teclado.", "zh-Hans": "无法创建键盘事件源。", "ja": "キーボードイベントソースを作成できません。", "ko": "키보드 이벤트 소스를 만들 수 없습니다.", "it": "Impossibile creare la sorgente eventi tastiera.", "tr": "Yazma için klavye olay kaynağı oluşturulamadı."],
        "error.pasteNotVerified": ["en": "Paste could not be verified. The transcript was left on the clipboard.", "ru": "Вставку не удалось проверить. Текст оставлен в буфере обмена.", "es": "No se pudo verificar el pegado. La transcripción quedó en el portapapeles.", "de": "Das Einfügen konnte nicht bestätigt werden. Der Text bleibt in der Zwischenablage.", "fr": "L’insertion n’a pas pu être vérifiée. Le texte a été laissé dans le presse-papiers.", "pt": "Não foi possível verificar a colagem. A transcrição ficou na área de transferência.", "zh-Hans": "无法验证粘贴结果。转写文本已保留在剪贴板中。", "ja": "貼り付けを確認できませんでした。文字起こしはクリップボードに残しました。", "ko": "붙여넣기를 확인할 수 없습니다. 변환 텍스트를 클립보드에 남겼습니다.", "it": "Impossibile verificare l'incolla. Il testo è rimasto negli appunti.", "tr": "Yapıştırma doğrulanamadı. Metin panoda bırakıldı."],
        "general.app": ["en": "App", "ru": "Приложение", "es": "App", "de": "App", "fr": "App", "pt": "App", "zh-Hans": "应用", "ja": "アプリ", "ko": "앱", "it": "App", "tr": "Uygulama"],
        "general.appearance": ["en": "Appearance", "ru": "Оформление", "es": "Apariencia", "de": "Erscheinungsbild", "fr": "Apparence", "pt": "Aparência", "zh-Hans": "外观", "ja": "外観", "ko": "모양", "it": "Aspetto", "tr": "Görünüm"],
        "general.launchAtLogin": ["en": "Launch at login", "ru": "Запускать при входе в систему", "es": "Abrir al iniciar sesión", "de": "Bei Anmeldung starten", "fr": "Lancer à la connexion", "pt": "Abrir ao iniciar sessão", "zh-Hans": "登录时启动", "ja": "ログイン時に起動", "ko": "로그인 시 실행", "it": "Avvia all'accesso", "tr": "Girişte başlat"],
        "general.menuBar": ["en": "Show menu bar icon", "ru": "Показывать иконку в строке меню", "es": "Mostrar icono en la barra de menús", "de": "Menüleistensymbol anzeigen", "fr": "Afficher l'icône dans la barre de menus", "pt": "Mostrar ícone na barra de menus", "zh-Hans": "显示菜单栏图标", "ja": "メニューバーにアイコンを表示", "ko": "메뉴 막대 아이콘 표시", "it": "Mostra icona nella barra dei menu", "tr": "Menü çubuğu simgesini göster"],
        "general.menuBarHiddenHint": ["en": "No Dock icon. To reopen: launch Dictabar again from Finder or Spotlight.", "ru": "Иконки в Dock нет. Открыть снова: запустите Dictabar из Finder или Spotlight.", "es": "Sin icono en el Dock. Para reabrir: lanza Dictabar desde Finder o Spotlight.", "de": "Kein Dock-Symbol. Erneut öffnen: Dictabar über Finder oder Spotlight starten.", "fr": "Pas d'icône dans le Dock. Pour rouvrir : lancez Dictabar depuis le Finder ou Spotlight.", "pt": "Sem ícone no Dock. Para reabrir: abra o Dictabar no Finder ou Spotlight.", "zh-Hans": "无程序坞图标。再次打开：从 Finder 或聚焦搜索启动 Dictabar。", "ja": "Dock にアイコンはありません。再表示は Finder か Spotlight から Dictabar を起動。", "ko": "Dock 아이콘 없음. 다시 열려면 Finder 또는 Spotlight에서 Dictabar 실행.", "it": "Nessuna icona nel Dock. Per riaprire: avvia Dictabar da Finder o Spotlight.", "tr": "Dock simgesi yok. Yeniden açmak için: Finder veya Spotlight’tan Dictabar’i başlatın."],
        "general.overlay": ["en": "Recording overlay", "ru": "Оверлей записи", "es": "Superposición de grabación", "de": "Aufnahme-Overlay", "fr": "Superposition d'enregistrement", "pt": "Overlay de gravação", "zh-Hans": "录音浮层", "ja": "録音オーバーレイ", "ko": "녹음 오버레이", "it": "Overlay di registrazione", "tr": "Kayıt katmanı"],
        "general.overlayPosition": ["en": "Overlay position", "ru": "Позиция оверлея", "es": "Posición de la superposición", "de": "Overlay-Position", "fr": "Position de la superposition", "pt": "Posição do overlay", "zh-Hans": "浮层位置", "ja": "オーバーレイの位置", "ko": "오버레이 위치", "it": "Posizione overlay", "tr": "Katman konumu"],
        "general.privatePreview": ["en": "Keep preview private (no text on overlay)", "ru": "Скрывать текст в превью оверлея", "es": "Mantener vista previa privada", "de": "Vorschau privat halten", "fr": "Garder l'aperçu privé", "pt": "Manter prévia privada", "zh-Hans": "预览保密（浮层不显示文字）", "ja": "プレビューを非表示", "ko": "미리보기 비공개", "it": "Mantieni anteprima privata", "tr": "Önizlemeyi gizli tut (katmanda metin yok)"],
        "general.showMic": ["en": "Show microphone label", "ru": "Показывать микрофон", "es": "Mostrar micrófono", "de": "Mikrofon anzeigen", "fr": "Afficher le microphone", "pt": "Mostrar microfone", "zh-Hans": "显示麦克风", "ja": "マイクを表示", "ko": "마이크 표시", "it": "Mostra microfono", "tr": "Mikrofon etiketini göster"],
        "general.showOverlay": ["en": "Show recording overlay", "ru": "Показывать оверлей записи", "es": "Mostrar superposición de grabación", "de": "Aufnahme-Overlay anzeigen", "fr": "Afficher la superposition d'enregistrement", "pt": "Mostrar overlay de gravação", "zh-Hans": "显示录音浮层", "ja": "録音オーバーレイを表示", "ko": "녹음 오버레이 표시", "it": "Mostra overlay di registrazione", "tr": "Kayıt katmanını göster"],
        "general.showPreview": ["en": "Show transcript preview after success", "ru": "Превью текста после успеха", "es": "Vista previa del texto tras el éxito", "de": "Transkriptvorschau nach Erfolg", "fr": "Aperçu du texte après succès", "pt": "Prévia do texto após sucesso", "zh-Hans": "成功后显示转写预览", "ja": "成功後に文字起こしプレビュー", "ko": "성공 후 받아쓰기 미리보기", "it": "Anteprima trascrizione dopo il successo", "tr": "Başarıdan sonra metin önizlemesi"],
        "general.showProvider": ["en": "Show provider name", "ru": "Показывать имя провайдера", "es": "Mostrar nombre del proveedor", "de": "Anbietername anzeigen", "fr": "Afficher le nom du fournisseur", "pt": "Mostrar nome do provedor", "zh-Hans": "显示服务商名称", "ja": "プロバイダー名を表示", "ko": "제공자 이름 표시", "it": "Mostra nome provider", "tr": "Sağlayıcı adını göster"],
        "general.showTimer": ["en": "Show timer while recording", "ru": "Показывать таймер во время записи", "es": "Mostrar temporizador al grabar", "de": "Timer während der Aufnahme anzeigen", "fr": "Afficher le minuteur pendant l'enregistrement", "pt": "Mostrar temporizador ao gravar", "zh-Hans": "录音时显示计时器", "ja": "録音中にタイマーを表示", "ko": "녹음 중 타이머 표시", "it": "Mostra timer durante la registrazione", "tr": "Kayıt sırasında zamanlayıcıyı göster"],
        "general.sounds": ["en": "Play start/stop sound", "ru": "Звук при старте и остановке", "es": "Reproducir sonido de inicio/parada", "de": "Start-/Stopp-Sound abspielen", "fr": "Jouer un son au début et à la fin", "pt": "Tocar som de início/fim", "zh-Hans": "播放开始/停止提示音", "ja": "開始/停止音を再生", "ko": "시작/중지 소리 재생", "it": "Riproduci suono avvio/stop", "tr": "Başlat/durdur sesi çal"],
        "general.uiLanguage": ["en": "Interface language", "ru": "Язык интерфейса", "es": "Idioma de la interfaz", "de": "Oberflächensprache", "fr": "Langue de l'interface", "pt": "Idioma da interface", "zh-Hans": "界面语言", "ja": "表示言語", "ko": "인터페이스 언어", "it": "Lingua dell'interfaccia", "tr": "Arayüz dili"],
        "insert.paste": ["en": "Paste via clipboard", "ru": "Вставка через буфер", "es": "Pegar con portapapeles", "de": "Über Zwischenablage einfügen", "fr": "Coller via le presse-papiers", "pt": "Colar via área de transferência", "zh-Hans": "通过剪贴板粘贴", "ja": "クリップボードで貼り付け", "ko": "클립보드로 붙여넣기", "it": "Incolla tramite appunti", "tr": "Pano ile yapıştır"],
        "insert.typing": ["en": "Simulated typing (no clipboard)", "ru": "Имитация набора (без буфера)", "es": "Escritura simulada (sin portapapeles)", "de": "Simulierte Eingabe (ohne Zwischenablage)", "fr": "Saisie simulée (sans presse-papiers)", "pt": "Digitação simulada (sem área de transferência)", "zh-Hans": "模拟键入（不用剪贴板）", "ja": "キー入力シミュレート（クリップボードなし）", "ko": "키 입력 시뮬레이션 (클립보드 없음)", "it": "Digitazione simulata (senza appunti)", "tr": "Simüle yazma (panosuz)"],
        "lang.ar": ["en": "Arabic", "ru": "Арабский", "es": "Arabic", "de": "Arabic", "fr": "Arabic", "pt": "Arabic", "zh-Hans": "Arabic", "ja": "Arabic", "ko": "Arabic", "it": "Arabic", "tr": "Arapça"],
        "lang.auto": ["en": "Same as spoken", "ru": "Как в речи", "es": "Same as spoken", "de": "Same as spoken", "fr": "Same as spoken", "pt": "Same as spoken", "zh-Hans": "Same as spoken", "ja": "Same as spoken", "ko": "Same as spoken", "it": "Same as spoken", "tr": "Konuşulan dil ile aynı"],
        "lang.bn": ["en": "Bengali", "ru": "Бенгальский", "es": "Bengali", "de": "Bengali", "fr": "Bengali", "pt": "Bengali", "zh-Hans": "Bengali", "ja": "Bengali", "ko": "Bengali", "it": "Bengali", "tr": "Bengalce"],
        "lang.de": ["en": "German", "ru": "Немецкий", "es": "German", "de": "German", "fr": "German", "pt": "German", "zh-Hans": "German", "ja": "German", "ko": "German", "it": "German", "tr": "Almanca"],
        "lang.en": ["en": "English", "ru": "Английский", "es": "English", "de": "English", "fr": "English", "pt": "English", "zh-Hans": "English", "ja": "English", "ko": "English", "it": "English", "tr": "İngilizce"],
        "lang.es": ["en": "Spanish", "ru": "Испанский", "es": "Spanish", "de": "Spanish", "fr": "Spanish", "pt": "Spanish", "zh-Hans": "Spanish", "ja": "Spanish", "ko": "Spanish", "it": "Spanish", "tr": "İspanyolca"],
        "lang.fr": ["en": "French", "ru": "Французский", "es": "French", "de": "French", "fr": "French", "pt": "French", "zh-Hans": "French", "ja": "French", "ko": "French", "it": "French", "tr": "Fransızca"],
        "lang.hi": ["en": "Hindi", "ru": "Хинди", "es": "Hindi", "de": "Hindi", "fr": "Hindi", "pt": "Hindi", "zh-Hans": "Hindi", "ja": "Hindi", "ko": "Hindi", "it": "Hindi", "tr": "Hintçe"],
        "lang.id": ["en": "Indonesian", "ru": "Индонезийский", "es": "Indonesian", "de": "Indonesian", "fr": "Indonesian", "pt": "Indonesian", "zh-Hans": "Indonesian", "ja": "Indonesian", "ko": "Indonesian", "it": "Indonesian", "tr": "Endonezce"],
        "lang.it": ["en": "Italian", "ru": "Итальянский", "es": "Italian", "de": "Italian", "fr": "Italian", "pt": "Italian", "zh-Hans": "Italian", "ja": "Italian", "ko": "Italian", "it": "Italian", "tr": "İtalyanca"],
        "lang.ja": ["en": "Japanese", "ru": "Японский", "es": "Japanese", "de": "Japanese", "fr": "Japanese", "pt": "Japanese", "zh-Hans": "Japanese", "ja": "Japanese", "ko": "Japanese", "it": "Japanese", "tr": "Japonca"],
        "lang.ko": ["en": "Korean", "ru": "Корейский", "es": "Korean", "de": "Korean", "fr": "Korean", "pt": "Korean", "zh-Hans": "Korean", "ja": "Korean", "ko": "Korean", "it": "Korean", "tr": "Korece"],
        "lang.nl": ["en": "Dutch", "ru": "Нидерландский", "es": "Dutch", "de": "Dutch", "fr": "Dutch", "pt": "Dutch", "zh-Hans": "Dutch", "ja": "Dutch", "ko": "Dutch", "it": "Dutch", "tr": "Felemenkçe"],
        "lang.pl": ["en": "Polish", "ru": "Польский", "es": "Polish", "de": "Polish", "fr": "Polish", "pt": "Polish", "zh-Hans": "Polish", "ja": "Polish", "ko": "Polish", "it": "Polish", "tr": "Lehçe"],
        "lang.pt": ["en": "Portuguese", "ru": "Португальский", "es": "Portuguese", "de": "Portuguese", "fr": "Portuguese", "pt": "Portuguese", "zh-Hans": "Portuguese", "ja": "Portuguese", "ko": "Portuguese", "it": "Portuguese", "tr": "Portekizce"],
        "lang.ru": ["en": "Russian", "ru": "Русский", "es": "Russian", "de": "Russian", "fr": "Russian", "pt": "Russian", "zh-Hans": "Russian", "ja": "Russian", "ko": "Russian", "it": "Russian", "tr": "Rusça"],
        "lang.tr": ["en": "Turkish", "ru": "Турецкий", "es": "Turkish", "de": "Turkish", "fr": "Turkish", "pt": "Turkish", "zh-Hans": "Turkish", "ja": "Turkish", "ko": "Turkish", "it": "Turkish", "tr": "Türkçe"],
        "lang.uk": ["en": "Ukrainian", "ru": "Украинский", "es": "Ukrainian", "de": "Ukrainian", "fr": "Ukrainian", "pt": "Ukrainian", "zh-Hans": "Ukrainian", "ja": "Ukrainian", "ko": "Ukrainian", "it": "Ukrainian", "tr": "Ukraynaca"],
        "lang.vi": ["en": "Vietnamese", "ru": "Вьетнамский", "es": "Vietnamese", "de": "Vietnamese", "fr": "Vietnamese", "pt": "Vietnamese", "zh-Hans": "Vietnamese", "ja": "Vietnamese", "ko": "Vietnamese", "it": "Vietnamese", "tr": "Vietnamca"],
        "lang.zh": ["en": "Chinese (Simplified)", "ru": "Китайский (упрощённый)", "es": "Chinese (Simplified)", "de": "Chinese (Simplified)", "fr": "Chinese (Simplified)", "pt": "Chinese (Simplified)", "zh-Hans": "Chinese (Simplified)", "ja": "Chinese (Simplified)", "ko": "Chinese (Simplified)", "it": "Chinese (Simplified)", "tr": "Çince (Basitleştirilmiş)"],
        "menu.cancel": ["en": "Cancel Dictation", "ru": "Отменить диктовку", "es": "Cancelar dictado", "de": "Diktat abbrechen", "fr": "Annuler la dictée", "pt": "Cancelar ditado", "zh-Hans": "取消听写", "ja": "キャンセル", "ko": "받아쓰기 취소", "it": "Annulla dettatura", "tr": "Dikteyi İptal Et"],
        "menu.retry": ["en": "Retry last dictation", "ru": "Повторить последнюю диктовку", "es": "Repetir último dictado", "de": "Letztes Diktat wiederholen", "fr": "Réessayer la dernière dictée", "pt": "Repetir último ditado", "zh-Hans": "重试上次听写", "ja": "最後の音声入力を再試行", "ko": "마지막 받아쓰기 다시 시도", "it": "Ripeti l’ultima dettatura", "tr": "Son dikteyi yeniden dene"],
        "menu.copyLast": ["en": "Copy last transcript", "ru": "Скопировать последний текст", "es": "Copiar última transcripción", "de": "Letztes Transkript kopieren", "fr": "Copier la dernière transcription", "pt": "Copiar última transcrição", "zh-Hans": "复制上次转写", "ja": "最後の文字起こしをコピー", "ko": "마지막 전사 복사", "it": "Copia l’ultima trascrizione", "tr": "Son transkripsiyonu kopyala"],
        "menu.provider": ["en": "Current Provider", "ru": "Текущий провайдер", "es": "Proveedor actual", "de": "Aktueller Anbieter", "fr": "Fournisseur actuel", "pt": "Provedor atual", "zh-Hans": "当前服务商", "ja": "現在のプロバイダー", "ko": "현재 제공자", "it": "Provider attuale", "tr": "Geçerli Sağlayıcı"],
        "menu.quit": ["en": "Quit Dictabar", "ru": "Выйти из Dictabar", "es": "Salir de Dictabar", "de": "Dictabar beenden", "fr": "Quitter Dictabar", "pt": "Sair do Dictabar", "zh-Hans": "退出 Dictabar", "ja": "Dictabar を終了", "ko": "Dictabar 종료", "it": "Esci da Dictabar", "tr": "Dictabar’ten Çık"],
        "menu.settings": ["en": "Settings…", "ru": "Настройки…", "es": "Ajustes…", "de": "Einstellungen…", "fr": "Réglages…", "pt": "Ajustes…", "zh-Hans": "设置…", "ja": "設定…", "ko": "설정…", "it": "Impostazioni…", "tr": "Ayarlar…"],
        "menu.startStop": ["en": "Start/Stop Dictation", "ru": "Старт/стоп диктовки", "es": "Iniciar/detener dictado", "de": "Diktat starten/stoppen", "fr": "Démarrer/arrêter la dictée", "pt": "Iniciar/parar ditado", "zh-Hans": "开始/停止听写", "ja": "ディクテーション開始/停止", "ko": "받아쓰기 시작/중지", "it": "Avvia/ferma dettatura", "tr": "Dikteyi Başlat/Durdur"],
        "menu.updates": ["en": "Check for Updates…", "ru": "Проверить обновления…", "es": "Buscar actualizaciones…", "de": "Nach Updates suchen…", "fr": "Rechercher des mises à jour…", "pt": "Verificar atualizações…", "zh-Hans": "检查更新…", "ja": "アップデートを確認…", "ko": "업데이트 확인…", "it": "Verifica aggiornamenti…", "tr": "Güncellemeleri Kontrol Et…"],
        "mode.hold": ["en": "Hold to dictate", "ru": "Удерживать для диктовки", "es": "Mantener para dictar", "de": "Halten zum Diktieren", "fr": "Maintenir pour dicter", "pt": "Segurar para ditar", "zh-Hans": "按住听写", "ja": "長押しでディクテーション", "ko": "누르고 받아쓰기", "it": "Tieni premuto per dettare", "tr": "Dikte için basılı tut"],
        "mode.toggle": ["en": "Press once to start, press again to stop", "ru": "Одно нажатие — старт, повторное — стоп", "es": "Pulsa una vez para iniciar, otra para detener", "de": "Einmal drücken zum Starten, erneut zum Stoppen", "fr": "Appuyer une fois pour démarrer, encore pour arrêter", "pt": "Pressione uma vez para iniciar, de novo para parar", "zh-Hans": "按一次开始，再按停止", "ja": "一度で開始、もう一度で停止", "ko": "한 번 시작, 다시 눌러 중지", "it": "Premi una volta per avviare, di nuovo per fermare", "tr": "Başlatmak için bir kez, durdurmak için tekrar bas"],
        "overlay.inserted": ["en": "Inserted", "ru": "Вставлено", "es": "Insertado", "de": "Eingefügt", "fr": "Inséré", "pt": "Inserido", "zh-Hans": "已插入", "ja": "挿入済み", "ko": "삽입됨", "it": "Inserito", "tr": "Eklendi"],
        "overlay.recording": ["en": "Recording", "ru": "Запись", "es": "Grabando", "de": "Aufnahme", "fr": "Enregistrement", "pt": "Gravando", "zh-Hans": "录音中", "ja": "録音中", "ko": "녹음 중", "it": "Registrazione", "tr": "Kayıt"],
        "overlay.transcribing": ["en": "Transcribing…", "ru": "Транскрибация…", "es": "Transcribiendo…", "de": "Transkription…", "fr": "Transcription…", "pt": "Transcrevendo…", "zh-Hans": "转写中…", "ja": "文字起こし中…", "ko": "변환 중…", "it": "Trascrizione…", "tr": "Yazıya dökülüyor…"],
        "perm.allowed": ["en": "Allowed", "ru": "Разрешено", "es": "Permitido", "de": "Erlaubt", "fr": "Autorisé", "pt": "Permitido", "zh-Hans": "已允许", "ja": "許可済み", "ko": "허용됨", "it": "Consentito", "tr": "İzin verildi"],
        "perm.ax": ["en": "Accessibility", "ru": "Универсальный доступ", "es": "Accesibilidad", "de": "Bedienungshilfen", "fr": "Accessibilité", "pt": "Acessibilidade", "zh-Hans": "辅助功能", "ja": "アクセシビリティ", "ko": "손쉬운 사용", "it": "Accessibilità", "tr": "Erişilebilirlik"],
        "perm.axDesc": ["en": "Lets Dictabar paste or type the transcript and cancel while another app is focused.", "ru": "Позволяет вставлять или вводить текст и отменять диктовку, когда активно другое приложение.", "es": "Permite pegar o escribir la transcripción y cancelar cuando otra app está activa.", "de": "Ermöglicht Einfügen oder Tippen und Abbrechen, während eine andere App aktiv ist.", "fr": "Permet de coller ou saisir la transcription et d’annuler lorsqu’une autre app est active.", "pt": "Permite colar ou digitar a transcrição e cancelar enquanto outro app está ativo.", "zh-Hans": "允许在其他应用处于焦点时粘贴或键入转写内容并取消听写。", "ja": "別のアプリがアクティブなときに文字起こしを貼り付け、入力、キャンセルできます。", "ko": "다른 앱이 활성화된 동안 변환 내용을 붙여넣거나 입력하고 취소할 수 있습니다.", "it": "Consente di incollare o digitare la trascrizione e annullare quando è attiva un'altra app.", "tr": "Başka bir uygulama etkinken metni yapıştırmayı, yazmayı ve iptal etmeyi sağlar."],
        "perm.denied": ["en": "Denied", "ru": "Запрещено", "es": "Denegado", "de": "Verweigert", "fr": "Refusé", "pt": "Negado", "zh-Hans": "已拒绝", "ja": "拒否", "ko": "거부됨", "it": "Negato", "tr": "Reddedildi"],
        "perm.done": ["en": "Done", "ru": "Готово", "es": "Listo", "de": "Fertig", "fr": "Terminé", "pt": "Concluído", "zh-Hans": "完成", "ja": "完了", "ko": "완료", "it": "Fatto", "tr": "Tamam"],
        "perm.enable": ["en": "Enable %@", "ru": "Включить %@", "es": "Activar %@", "de": "%@ aktivieren", "fr": "Activer %@", "pt": "Ativar %@", "zh-Hans": "启用 %@", "ja": "%@ を有効化", "ko": "%@ 사용", "it": "Abilita %@", "tr": "%@ etkinleştir"],
        "perm.hint1": ["en": "After allowing a permission, return here — status updates automatically.", "ru": "После выдачи разрешения вернитесь сюда — статус обновится сам.", "es": "Tras permitir, vuelve aquí: el estado se actualiza solo.", "de": "Nach der Erlaubnis hierher zurück — Status aktualisiert sich.", "fr": "Après autorisation, revenez ici — le statut se met à jour.", "pt": "Depois de permitir, volte aqui — o status atualiza sozinho.", "zh-Hans": "授权后回到这里，状态会自动更新。", "ja": "許可後に戻ると状態が自動更新されます。", "ko": "허용 후 돌아오면 상태가 자동 갱신됩니다.", "it": "Dopo aver concesso, torna qui: lo stato si aggiorna.", "tr": "İzin verdikten sonra buraya dönün — durum otomatik güncellenir."],
        "perm.hint2": ["en": "If a dialog does not appear, open System Settings with the button and enable Dictabar.", "ru": "Если диалог не появился — откройте Системные настройки кнопкой и включите Dictabar.", "es": "Si no aparece el diálogo, abre Ajustes del Sistema y activa Dictabar.", "de": "Wenn kein Dialog erscheint: Systemeinstellungen öffnen und Dictabar aktivieren.", "fr": "Si aucun dialogue n'apparaît, ouvrez Réglages Système et activez Dictabar.", "pt": "Se o diálogo não aparecer, abra Ajustes do Sistema e ative o Dictabar.", "zh-Hans": "若未弹出对话框，请点按钮打开系统设置并启用 Dictabar。", "ja": "ダイアログが出ない場合は設定を開き Dictabar を有効にしてください。", "ko": "대화상자가 없으면 설정에서 Dictabar를 켜세요.", "it": "Se non compare il dialogo, apri Impostazioni di Sistema e abilita Dictabar.", "tr": "İletişim kutusu çıkmazsa Sistem Ayarları’nı açıp Dictabar’i etkinleştirin."],
        "perm.im": ["en": "Input Monitoring", "ru": "Мониторинг ввода", "es": "Monitorización de entrada", "de": "Eingabeüberwachung", "fr": "Surveillance des entrées", "pt": "Monitoramento de entrada", "zh-Hans": "输入监控", "ja": "入力モニタリング", "ko": "입력 모니터링", "it": "Monitoraggio input", "tr": "Giriş İzleme"],
        "perm.imDesc": ["en": "Needed for the Right ⌘ / Right ⌥ dictation shortcuts.", "ru": "Нужен для запуска диктовки через Right ⌘ / Right ⌥.", "es": "Necesario para los atajos de dictado Right ⌘ / Right ⌥.", "de": "Für die Diktat-Kürzel Right ⌘ / Right ⌥ erforderlich.", "fr": "Nécessaire pour les raccourcis de dictée Right ⌘ / Right ⌥.", "pt": "Necessário para os atalhos de ditado Right ⌘ / Right ⌥.", "zh-Hans": "Right ⌘ / Right ⌥ 听写快捷键需要此权限。", "ja": "Right ⌘ / Right ⌥ のディクテーションに必要です。", "ko": "Right ⌘ / Right ⌥ 받아쓰기 단축키에 필요합니다.", "it": "Serve per le scorciatoie di dettatura Right ⌘ / Right ⌥.", "tr": "Sağ ⌘ / Sağ ⌥ dikte kısayolları için gereklidir."],
        "perm.imDragAction": ["en": "Drag Dictabar", "ru": "Перетащить Dictabar", "es": "Arrastrar Dictabar", "de": "Dictabar ziehen", "fr": "Glisser Dictabar", "pt": "Arrastar Dictabar", "zh-Hans": "拖动 Dictabar", "ja": "Dictabar をドラッグ", "ko": "Dictabar 드래그", "it": "Trascina Dictabar", "tr": "Dictabar'ı sürükle"],
        "perm.imDragHint": ["en": "Open Input Monitoring, then drag this card into its app list.", "ru": "Откройте Input Monitoring и перетащите эту карточку в список приложений.", "es": "Abre Monitorización de entrada y arrastra esta tarjeta a la lista.", "de": "Eingabeüberwachung öffnen und diese Karte in die App-Liste ziehen.", "fr": "Ouvrez Surveillance des entrées et glissez cette carte dans la liste.", "pt": "Abra Monitoramento de entrada e arraste este cartão para a lista.", "zh-Hans": "打开输入监控，然后将此卡片拖入应用列表。", "ja": "入力モニタリングを開き、このカードをアプリ一覧へドラッグします。", "ko": "입력 모니터링을 열고 이 카드를 앱 목록으로 드래그하세요.", "it": "Apri Monitoraggio input e trascina questa scheda nell'elenco.", "tr": "Giriş İzleme'yi açın ve bu kartı uygulama listesine sürükleyin."],
        "perm.imDragTitle": ["en": "Drag Dictabar into Input Monitoring", "ru": "Перетащите Dictabar в Input Monitoring", "es": "Arrastra Dictabar a Monitorización de entrada", "de": "Dictabar in die Eingabeüberwachung ziehen", "fr": "Glissez Dictabar dans Surveillance des entrées", "pt": "Arraste Dictabar para Monitoramento de entrada", "zh-Hans": "将 Dictabar 拖入输入监控", "ja": "Dictabar を入力モニタリングへドラッグ", "ko": "Dictabar를 입력 모니터링으로 드래그", "it": "Trascina Dictabar in Monitoraggio input", "tr": "Dictabar'ı Giriş İzleme'ye sürükleyin"],
        "perm.imNoteOff": ["en": "Custom shortcuts use Carbon hotkeys (no Input Monitoring).", "ru": "Свой шорткат через Carbon (мониторинг ввода не нужен).", "es": "Los atajos personalizados usan Carbon (sin Monitorización).", "de": "Eigene Kürzel nutzen Carbon (keine Eingabeüberwachung).", "fr": "Les raccourcis perso utilisent Carbon (pas de Surveillance).", "pt": "Atalhos personalizados usam Carbon (sem Monitoramento).", "zh-Hans": "自定义快捷键使用 Carbon（无需输入监控）。", "ja": "カスタムショートカットは Carbon 使用（入力モニタリング不要）。", "ko": "사용자 지정 단축키는 Carbon 사용(입력 모니터링 불필요).", "it": "Le scorciatoie personalizzate usano Carbon (senza monitoraggio).", "tr": "Özel kısayollar Carbon kullanır (Giriş İzleme gerekmez)."],
        "perm.imNoteOn": ["en": "Input Monitoring is needed for Right ⌘ / Right ⌥ shortcuts.", "ru": "Мониторинг ввода нужен для Right ⌘ / Right ⌥.", "es": "Monitorización de entrada necesaria para Right ⌘ / Right ⌥.", "de": "Eingabeüberwachung nötig für Right ⌘ / Right ⌥.", "fr": "Surveillance des entrées requise pour Right ⌘ / Right ⌥.", "pt": "Monitoramento de entrada necessário para Right ⌘ / Right ⌥.", "zh-Hans": "Right ⌘ / Right ⌥ 需要输入监控。", "ja": "Right ⌘ / Right ⌥ には入力モニタリングが必要です。", "ko": "Right ⌘ / Right ⌥ 에는 입력 모니터링이 필요합니다.", "it": "Il monitoraggio input serve per Right ⌘ / Right ⌥.", "tr": "Sağ ⌘ / Sağ ⌥ için Giriş İzleme gerekir."],
        "perm.intro": ["en": "Dictabar only asks for what it needs. Each button opens the native macOS dialog or System Settings.", "ru": "Dictabar запрашивает только необходимое. Каждая кнопка открывает системный диалог или Настройки.", "es": "Dictabar solo pide lo necesario. Cada botón abre el diálogo nativo o Ajustes del sistema.", "de": "Dictabar fragt nur das Nötige an. Jeder Knopf öffnet den Systemdialog oder die Systemeinstellungen.", "fr": "Dictabar ne demande que le nécessaire. Chaque bouton ouvre le dialogue macOS ou Réglages Système.", "pt": "O Dictabar pede só o necessário. Cada botão abre o diálogo nativo ou Ajustes do Sistema.", "zh-Hans": "Dictabar 只请求必要权限。每个按钮会打开系统对话框或系统设置。", "ja": "必要な権限のみ要求します。各ボタンでシステムのダイアログまたは設定を開きます。", "ko": "필요한 권한만 요청합니다. 각 버튼은 시스템 대화상자 또는 설정을 엽니다.", "it": "Dictabar chiede solo il necessario. Ogni pulsante apre il dialogo di sistema o Impostazioni di Sistema.", "tr": "Dictabar yalnızca ihtiyacı olanı ister. Her düğme sistem iletişim kutusunu veya Sistem Ayarları’nı açar."],
        "perm.later": ["en": "Later", "ru": "Позже", "es": "Después", "de": "Später", "fr": "Plus tard", "pt": "Depois", "zh-Hans": "稍后", "ja": "後で", "ko": "나중에", "it": "Dopo", "tr": "Sonra"],
        "perm.mic": ["en": "Microphone", "ru": "Микрофон", "es": "Micrófono", "de": "Mikrofon", "fr": "Microphone", "pt": "Microfone", "zh-Hans": "麦克风", "ja": "マイク", "ko": "마이크", "it": "Microfono", "tr": "Mikrofon"],
        "perm.micDesc": ["en": "Records audio only while you are dictating. Never in the background.", "ru": "Записывает звук только во время диктовки. Не в фоне.", "es": "Graba audio solo mientras dictas. Nunca en segundo plano.", "de": "Nimmt nur während des Diktats auf. Nie im Hintergrund.", "fr": "Enregistre uniquement pendant la dictée. Jamais en arrière-plan.", "pt": "Grava áudio só enquanto você dita. Nunca em segundo plano.", "zh-Hans": "仅在听写时录音，不会在后台录音。", "ja": "ディクテーション中のみ録音。バックグラウンドでは録音しません。", "ko": "받아쓰는 동안에만 녹음합니다. 백그라운드에서는 녹음하지 않습니다.", "it": "Registra audio solo durante la dettatura. Mai in background.", "tr": "Yalnızca dikte ederken ses kaydeder. Arka planda asla."],
        "perm.notEnabled": ["en": "Not enabled", "ru": "Не включено", "es": "No activado", "de": "Nicht aktiviert", "fr": "Non activé", "pt": "Não ativado", "zh-Hans": "未启用", "ja": "未有効", "ko": "사용 안 함", "it": "Non abilitato", "tr": "Açık değil"],
        "perm.openFull": ["en": "Open Settings…", "ru": "Открыть настройки…", "es": "Abrir ajustes…", "de": "Einstellungen öffnen…", "fr": "Ouvrir les réglages…", "pt": "Abrir ajustes…", "zh-Hans": "打开设置…", "ja": "設定を開く…", "ko": "설정 열기…", "it": "Apri impostazioni…", "tr": "Ayarları Aç…"],
        "perm.openSettings": ["en": "Open Settings", "ru": "Открыть Настройки", "es": "Abrir Ajustes", "de": "Einstellungen öffnen", "fr": "Ouvrir Réglages", "pt": "Abrir Ajustes", "zh-Hans": "打开设置", "ja": "設定を開く", "ko": "설정 열기", "it": "Apri Impostazioni", "tr": "Ayarları Aç"],
        "perm.optional": ["en": "Optional", "ru": "Необязательно", "es": "Opcional", "de": "Optional", "fr": "Facultatif", "pt": "Opcional", "zh-Hans": "可选", "ja": "任意", "ko": "선택", "it": "Facoltativo", "tr": "İsteğe bağlı"],
        "perm.progress": ["en": "%d of %d enabled", "ru": "%d из %d включено", "es": "%d de %d activados", "de": "%d von %d aktiviert", "fr": "%d sur %d activés", "pt": "%d de %d ativados", "zh-Hans": "已启用 %d / %d", "ja": "%d / %d 有効", "ko": "%d / %d 사용 중", "it": "%d di %d attivi", "tr": "%d / %d etkin"],
        "perm.ready": ["en": "Ready to dictate", "ru": "Готово к диктовке", "es": "Listo para dictar", "de": "Bereit zum Diktieren", "fr": "Prêt à dicter", "pt": "Pronto para ditar", "zh-Hans": "可以听写", "ja": "ディクテーション可能", "ko": "받아쓰기 준비됨", "it": "Pronto per dettare", "tr": "Dikteye hazır"],
        "perm.required": ["en": "Required", "ru": "Обязательно", "es": "Obligatorio", "de": "Erforderlich", "fr": "Obligatoire", "pt": "Obrigatório", "zh-Hans": "必需", "ja": "必須", "ko": "필수", "it": "Obbligatorio", "tr": "Gerekli"],
        "perm.setup": ["en": "Setup needed", "ru": "Нужна настройка", "es": "Configuración necesaria", "de": "Einrichtung erforderlich", "fr": "Configuration requise", "pt": "Configuração necessária", "zh-Hans": "需要设置", "ja": "設定が必要", "ko": "설정 필요", "it": "Configurazione necessaria", "tr": "Kurulum gerekli"],
        "perm.title": ["en": "Permissions", "ru": "Разрешения", "es": "Permisos", "de": "Berechtigungen", "fr": "Autorisations", "pt": "Permissões", "zh-Hans": "权限", "ja": "権限", "ko": "권한", "it": "Autorizzazioni", "tr": "İzinler"],
        "perm.welcome": ["en": "Welcome to Dictabar", "ru": "Добро пожаловать в Dictabar", "es": "Bienvenido a Dictabar", "de": "Willkommen bei Dictabar", "fr": "Bienvenue dans Dictabar", "pt": "Bem-vindo ao Dictabar", "zh-Hans": "欢迎使用 Dictabar", "ja": "Dictabar へようこそ", "ko": "Dictabar에 오신 것을 환영합니다", "it": "Benvenuto in Dictabar", "tr": "Dictabar’e hoş geldiniz"],
        "perm.welcomeBody": ["en": "Enable a couple of macOS permissions so dictation can record and insert text.", "ru": "Включите несколько разрешений macOS, чтобы диктовка могла записывать и вставлять текст.", "es": "Activa unos permisos de macOS para grabar e insertar texto.", "de": "Aktiviere ein paar macOS-Berechtigungen zum Aufnehmen und Einfügen.", "fr": "Activez quelques autorisations macOS pour enregistrer et insérer du texte.", "pt": "Ative algumas permissões do macOS para gravar e inserir texto.", "zh-Hans": "启用几项 macOS 权限以便录音并插入文字。", "ja": "録音と挿入のために macOS の権限を有効にしてください。", "ko": "녹음과 삽입을 위해 macOS 권한을 켜 주세요.", "it": "Abilita alcune autorizzazioni macOS per registrare e inserire testo.", "tr": "Kayıt ve metin ekleme için birkaç macOS iznini açın."],
        "pos.bottomCenter": ["en": "Bottom center", "ru": "Снизу по центру", "es": "Abajo centro", "de": "Unten Mitte", "fr": "Bas centre", "pt": "Inferior centro", "zh-Hans": "底部居中", "ja": "下中央", "ko": "하단 중앙", "it": "Basso centro", "tr": "Alt orta"],
        "pos.bottomLeft": ["en": "Bottom left", "ru": "Снизу слева", "es": "Abajo izquierda", "de": "Unten links", "fr": "Bas gauche", "pt": "Inferior esquerda", "zh-Hans": "左下", "ja": "左下", "ko": "왼쪽 아래", "it": "Basso sinistra", "tr": "Alt sol"],
        "pos.bottomRight": ["en": "Bottom right", "ru": "Снизу справа", "es": "Abajo derecha", "de": "Unten rechts", "fr": "Bas droite", "pt": "Inferior direita", "zh-Hans": "右下", "ja": "右下", "ko": "오른쪽 아래", "it": "Basso destra", "tr": "Alt sağ"],
        "pos.topCenter": ["en": "Top center", "ru": "Сверху по центру", "es": "Arriba centro", "de": "Oben Mitte", "fr": "Haut centre", "pt": "Superior centro", "zh-Hans": "顶部居中", "ja": "上中央", "ko": "상단 중앙", "it": "Alto centro", "tr": "Üst orta"],
        "pos.topLeft": ["en": "Top left", "ru": "Сверху слева", "es": "Arriba izquierda", "de": "Oben links", "fr": "Haut gauche", "pt": "Superior esquerda", "zh-Hans": "左上", "ja": "左上", "ko": "왼쪽 위", "it": "Alto sinistra", "tr": "Üst sol"],
        "pos.topRight": ["en": "Top right", "ru": "Сверху справа", "es": "Arriba derecha", "de": "Oben rechts", "fr": "Haut droite", "pt": "Superior direita", "zh-Hans": "右上", "ja": "右上", "ko": "오른쪽 위", "it": "Alto destra", "tr": "Üst sağ"],
        "preset.custom": ["en": "Custom shortcut", "ru": "Свой шорткат", "es": "Atajo personalizado", "de": "Benutzerdefiniertes Kürzel", "fr": "Raccourci personnalisé", "pt": "Atalho personalizado", "zh-Hans": "自定义快捷键", "ja": "カスタムショートカット", "ko": "사용자 지정 단축키", "it": "Scorciatoia personalizzata", "tr": "Özel kısayol"],
        "preset.rightCommand": ["en": "Right Command", "ru": "Правый Command", "es": "Command derecho", "de": "Rechte Command-Taste", "fr": "Commande droite", "pt": "Command direito", "zh-Hans": "右 Command", "ja": "右 Command", "ko": "오른쪽 Command", "it": "Command destro", "tr": "Sağ Command"],
        "preset.rightOption": ["en": "Right Option", "ru": "Правый Option", "es": "Option derecho", "de": "Rechte Option-Taste", "fr": "Option droite", "pt": "Option direito", "zh-Hans": "右 Option", "ja": "右 Option", "ko": "오른쪽 Option", "it": "Option destro", "tr": "Sağ Option"],
        "prov.apiKey": ["en": "API key", "ru": "API-ключ", "es": "Clave API", "de": "API-Schlüssel", "fr": "Clé API", "pt": "Chave API", "zh-Hans": "API 密钥", "ja": "API キー", "ko": "API 키", "it": "Chiave API", "tr": "API anahtarı"],
        "prov.baseURL": ["en": "Base URL", "ru": "Базовый URL", "es": "URL base", "de": "Basis-URL", "fr": "URL de base", "pt": "URL base", "zh-Hans": "基础 URL", "ja": "ベース URL", "ko": "기본 URL", "it": "URL di base", "tr": "Temel URL"],
        "prov.clear": ["en": "Clear key", "ru": "Очистить ключ", "es": "Borrar clave", "de": "Schlüssel löschen", "fr": "Effacer la clé", "pt": "Limpar chave", "zh-Hans": "清除密钥", "ja": "キーを消去", "ko": "키 지우기", "it": "Cancella chiave", "tr": "Anahtarı sil"],
        "prov.codeSwitch": ["en": "Code switching", "ru": "Переключение языков", "es": "Cambio de código", "de": "Code-Switching", "fr": "Alternance codique", "pt": "Alternância de código", "zh-Hans": "语码转换", "ja": "コードスイッチング", "ko": "코드 전환", "it": "Code switching", "tr": "Kod değiştirme"],
        "prov.enhPunct": ["en": "Enhanced punctuation", "ru": "Улучшенная пунктуация", "es": "Puntuación mejorada", "de": "Erweiterte Zeichensetzung", "fr": "Ponctuation améliorée", "pt": "Pontuação aprimorada", "zh-Hans": "增强标点", "ja": "強化句読点", "ko": "향상된 문장 부호", "it": "Punteggiatura avanzata", "tr": "Gelişmiş noktalama"],
        "prov.connection": ["en": "Connection", "ru": "Подключение", "es": "Conexión", "de": "Verbindung", "fr": "Connexion", "pt": "Conexão", "zh-Hans": "连接", "ja": "接続", "ko": "연결", "it": "Connessione", "tr": "Bağlantı"],
        "prov.getKey": ["en": "Get API key", "ru": "Получить API-ключ", "es": "Obtener clave API", "de": "API-Schlüssel abrufen", "fr": "Obtenir une clé API", "pt": "Obter chave de API", "zh-Hans": "获取 API 密钥", "ja": "APIキーを取得", "ko": "API 키 받기", "it": "Ottieni chiave API", "tr": "API anahtarı al"],
        "prov.languagesCount": ["en": "Languages · %@", "ru": "Языки · %@", "es": "Idiomas · %@", "de": "Sprachen · %@", "fr": "Langues · %@", "pt": "Idiomas · %@", "zh-Hans": "语言 · %@", "ja": "言語 · %@", "ko": "언어 · %@", "it": "Lingue · %@", "tr": "Diller · %@"],
        "prov.languageWarning": ["en": "The selected dictation language is not supported by this model.", "ru": "Выбранный язык диктовки не поддерживается этой моделью.", "es": "El idioma de dictado seleccionado no es compatible con este modelo.", "de": "Die gewählte Diktiersprache wird von diesem Modell nicht unterstützt.", "fr": "La langue de dictée sélectionnée n’est pas prise en charge par ce modèle.", "pt": "O idioma de ditado selecionado não é compatível com este modelo.", "zh-Hans": "此模型不支持所选听写语言。", "ja": "選択した音声入力言語はこのモデルでサポートされていません。", "ko": "선택한 받아쓰기 언어는 이 모델에서 지원되지 않습니다.", "it": "La lingua di dettatura selezionata non è supportata da questo modello.", "tr": "Seçilen dikte dili bu model tarafından desteklenmiyor."],
        "prov.model": ["en": "Model", "ru": "Модель", "es": "Modelo", "de": "Modell", "fr": "Modèle", "pt": "Modelo", "zh-Hans": "模型", "ja": "モデル", "ko": "모델", "it": "Modello", "tr": "Model"],
        "prov.notConfigured": ["en": "Status: Not configured", "ru": "Статус: не настроено", "es": "Estado: No configurado", "de": "Status: Nicht konfiguriert", "fr": "État : Non configuré", "pt": "Status: Não configurado", "zh-Hans": "状态：未配置", "ja": "状態: 未設定", "ko": "상태: 구성되지 않음", "it": "Stato: Non configurato", "tr": "Durum: Yapılandırılmadı"],
        "prov.numerals": ["en": "Numerals", "ru": "Числа", "es": "Números", "de": "Ziffern", "fr": "Chiffres", "pt": "Numerais", "zh-Hans": "数字", "ja": "数字", "ko": "숫자", "it": "Numeri", "tr": "Sayılar"],
        "prov.provider": ["en": "Provider", "ru": "Провайдер", "es": "Proveedor", "de": "Anbieter", "fr": "Fournisseur", "pt": "Provedor", "zh-Hans": "服务商", "ja": "プロバイダー", "ko": "제공자", "it": "Provider", "tr": "Sağlayıcı"],
        "prov.options": ["en": "Provider options", "ru": "Параметры провайдера", "es": "Opciones del proveedor", "de": "Anbieteroptionen", "fr": "Options du fournisseur", "pt": "Opções do provedor", "zh-Hans": "服务商选项", "ja": "プロバイダーオプション", "ko": "제공자 옵션", "it": "Opzioni provider", "tr": "Sağlayıcı seçenekleri"],
        "prov.punct": ["en": "Punctuation", "ru": "Пунктуация", "es": "Puntuación", "de": "Zeichensetzung", "fr": "Ponctuation", "pt": "Pontuação", "zh-Hans": "标点", "ja": "句読点", "ko": "문장 부호", "it": "Punteggiatura", "tr": "Noktalama"],
        "prov.ready": ["en": "Status: Ready", "ru": "Статус: готово", "es": "Estado: Listo", "de": "Status: Bereit", "fr": "État : Prêt", "pt": "Status: Pronto", "zh-Hans": "状态：就绪", "ja": "状態: 準備完了", "ko": "상태: 준비됨", "it": "Stato: Pronto", "tr": "Durum: Hazır"],
        "prov.reload": ["en": "Reload saved key", "ru": "Загрузить сохранённый ключ", "es": "Recargar clave guardada", "de": "Gespeicherten Schlüssel laden", "fr": "Recharger la clé enregistrée", "pt": "Recarregar chave salva", "zh-Hans": "重新加载已保存密钥", "ja": "保存済みキーを再読込", "ko": "저장된 키 다시 불러오기", "it": "Ricarica chiave salvata", "tr": "Kayıtlı anahtarı yeniden yükle"],
        "prov.save": ["en": "Save key", "ru": "Сохранить ключ", "es": "Guardar clave", "de": "Schlüssel speichern", "fr": "Enregistrer la clé", "pt": "Salvar chave", "zh-Hans": "保存密钥", "ja": "キーを保存", "ko": "키 저장", "it": "Salva chiave", "tr": "Anahtarı kaydet"],
        "prov.saved": ["en": "Status: Saved locally", "ru": "Статус: сохранено локально", "es": "Estado: Guardado localmente", "de": "Status: Lokal gespeichert", "fr": "État : Enregistré localement", "pt": "Status: Salvo localmente", "zh-Hans": "状态：已保存到本地", "ja": "状態: ローカルに保存済み", "ko": "상태: 로컬에 저장됨", "it": "Stato: Salvato localmente", "tr": "Durum: Yerel olarak kaydedildi"],
        "prov.searchLanguages": ["en": "Search languages", "ru": "Поиск языков", "es": "Buscar idiomas", "de": "Sprachen suchen", "fr": "Rechercher des langues", "pt": "Buscar idiomas", "zh-Hans": "搜索语言", "ja": "言語を検索", "ko": "언어 검색", "it": "Cerca lingue", "tr": "Dil ara"],
        "prov.smartFmt": ["en": "Smart formatting", "ru": "Умное форматирование", "es": "Formato inteligente", "de": "Intelligente Formatierung", "fr": "Mise en forme intelligente", "pt": "Formatação inteligente", "zh-Hans": "智能格式", "ja": "スマート書式", "ko": "스마트 서식", "it": "Formattazione smart", "tr": "Akıllı biçimlendirme"],
        "prov.supportedLanguages": ["en": "Supported languages", "ru": "Поддерживаемые языки", "es": "Idiomas compatibles", "de": "Unterstützte Sprachen", "fr": "Langues prises en charge", "pt": "Idiomas compatíveis", "zh-Hans": "支持的语言", "ja": "対応言語", "ko": "지원 언어", "it": "Lingue supportate", "tr": "Desteklenen diller"],
        "section.advanced": ["en": "Advanced", "ru": "Дополнительно", "es": "Avanzado", "de": "Erweitert", "fr": "Avancé", "pt": "Avançado", "zh-Hans": "高级", "ja": "詳細", "ko": "고급", "it": "Avanzate", "tr": "Gelişmiş"],
        "section.dictation": ["en": "Dictation", "ru": "Диктовка", "es": "Dictado", "de": "Diktat", "fr": "Dictée", "pt": "Ditado", "zh-Hans": "听写", "ja": "ディクテーション", "ko": "받아쓰기", "it": "Dettatura", "tr": "Dikte"],
        "section.general": ["en": "General", "ru": "Основное", "es": "General", "de": "Allgemein", "fr": "Général", "pt": "Geral", "zh-Hans": "通用", "ja": "一般", "ko": "일반", "it": "Generale", "tr": "Genel"],
        "section.permissions": ["en": "Permissions", "ru": "Разрешения", "es": "Permisos", "de": "Berechtigungen", "fr": "Autorisations", "pt": "Permissões", "zh-Hans": "权限", "ja": "権限", "ko": "권한", "it": "Autorizzazioni", "tr": "İzinler"],
        "section.providers": ["en": "Providers", "ru": "Провайдеры", "es": "Proveedores", "de": "Anbieter", "fr": "Fournisseurs", "pt": "Provedores", "zh-Hans": "服务商", "ja": "プロバイダー", "ko": "제공자", "it": "Provider", "tr": "Sağlayıcılar"],
        "section.updates": ["en": "Updates", "ru": "Обновления", "es": "Actualizaciones", "de": "Updates", "fr": "Mises à jour", "pt": "Atualizações", "zh-Hans": "更新", "ja": "アップデート", "ko": "업데이트", "it": "Aggiornamenti", "tr": "Güncellemeler"],
        "upd.check": ["en": "Check for updates", "ru": "Проверить обновления", "es": "Buscar actualizaciones", "de": "Nach Updates suchen", "fr": "Rechercher des mises à jour", "pt": "Verificar atualizações", "zh-Hans": "检查更新", "ja": "アップデートを確認", "ko": "업데이트 확인", "it": "Verifica aggiornamenti", "tr": "Güncellemeleri kontrol et"],
        "upd.checkOnLaunch": ["en": "Check for updates on launch", "ru": "Проверять обновления при запуске", "es": "Buscar actualizaciones al iniciar", "de": "Beim Start nach Updates suchen", "fr": "Vérifier les mises à jour au lancement", "pt": "Verificar atualizações ao iniciar", "zh-Hans": "启动时检查更新", "ja": "起動時にアップデートを確認", "ko": "시작 시 업데이트 확인", "it": "Controlla aggiornamenti all'avvio", "tr": "Açılışta güncellemeleri kontrol et"],
        "upd.checking": ["en": "Checking…", "ru": "Проверка…", "es": "Buscando…", "de": "Suche…", "fr": "Recherche…", "pt": "Verificando…", "zh-Hans": "检查中…", "ja": "確認中…", "ko": "확인 중…", "it": "Controllo…", "tr": "Kontrol ediliyor…"],
        "upd.openDownload": ["en": "Open download", "ru": "Открыть загрузку", "es": "Abrir descarga", "de": "Download öffnen", "fr": "Ouvrir le téléchargement", "pt": "Abrir download", "zh-Hans": "打开下载", "ja": "ダウンロードを開く", "ko": "다운로드 열기", "it": "Apri download", "tr": "İndirmeyi aç"],
        "upd.prereleases": ["en": "Include pre-releases", "ru": "Включать пре-релизы", "es": "Incluir prelanzamientos", "de": "Vorabversionen einbeziehen", "fr": "Inclure les préversions", "pt": "Incluir pré-lançamentos", "zh-Hans": "包含预发布版", "ja": "プレリリースを含める", "ko": "사전 출시 포함", "it": "Includi pre-release", "tr": "Ön sürümleri dahil et"],
    ]
}
